### ISSUE TITLE
Some sorters have a high verbosity event with debug=False

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikesorters#10]
I'm trying to catch the stdout, but with Popen you can read the stdout once the process is finished.

@samuelgarcia do you know of an alternative?

**Comment by magland** [comment]
Not sure if this is what you are referring to but here's how I capture standard output (not sure how it works in notebook)

```
runtime_capture = ConsoleCapture()

runtime_capture.start_capturing()
# do arbitrary python stuff
runtime_capture.stop_capturing()

console_output = runtime_capture.consoleOut()
```

where ConsoleCapture() is here: https://github.com/flatironinstitute/spikeforest/blob/master/mountaintools/mlprocessors/consolecapture.py

You can grab it and modify it as you like.

**Comment by samuelgarcia** [comment]
Thank for this link, I think we could take this ConsoleCapture and extend it with \_\_enter\_\_ and \_\_exit\_\_ the context manager of python.

**Comment by magland** [comment]
I agree. I am adding it to my todo list on spikeforest, but if somebody
wants to tackle it first let me know.

**Comment by alejoe91** [comment]
This fixes MS4 https://github.com/SpikeInterface/spikesorters/pull/22

**Comment by alejoe91** [comment]
@samuelgarcia do you have time to propagate the ShellScript to klusta, spyking-circus, kilosort, and kilosort2?

**Comment by samuelgarcia** [comment]
@alejoe91 : not in July. I am in holiday in august, I can do it ilate august or early setptember.
there is not urgency.

**Comment by alejoe91** [comment]
ok :+1: I think I can work on it in September as well :)

**Comment by alejoe91** [comment]
now both CLI and Matlab sorters use ShellScript. Can I close this?

**Comment by samuelgarcia** [comment]
I think yes.
