### ISSUE TITLE
pass minfr_goodchannels@KiloSort2 to ss.run_kilosort2 

### ISSUE THREAD

**Issue by gmaggi** [SpikeInterface/spikesorters#101]
Hi,

I am trying to pass **minfr_goodchannels** to `ss.run_kilosort2` function (no GUI), but this throws an error: "Bad parameters"
Apparently, the error comes from here: https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/basesorter.py#L106
This seems to check whether the parameter-key is in the default param-dict, but as this does not find it, it crashes. And indeed, the default parameters-dict does not include minfr_goodchannels:

`python -c "import spikeinterface.sorters as ss; print(ss.get_default_params('kilosort2'))"
{'detect_threshold': 5, 'projection_threshold': [10, 4], 'preclust_threshold': 8, 'car': True, 'minFR': 0.1, 'electrode_dimensions': None, 'freq_min': 150, 'sigmaMask': 30, 'nPCs': 3}`

do I miss anything to pass minfr_goodchannels to `run_kilosort2(...)`

**spikeinterface version: 0.9.1**

Many thanks,
Giuliano.

**Comment by alejoe91** [comment]
Hi! You should install spikesorterd from master. We will make a new release soon :)

**Comment by gmaggi** [comment]
Thanks for the prompt reply!
Just to make sure, should I wait for the new release, or the current master already solve my issue?

**Comment by alejoe91** [comment]
Already fixed in master :) so you should install from source

**Comment by alejoe91** [comment]
@gmaggi we'll make a new release probably tomorrow :)

**Comment by nerf-common** [comment]
Thanks for the note @alejoe91 !
Another remark, this time is about KiloSort(**1**). 

It seems to me that Nfilt can not be passed to the params in https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort/kilosort.py#L30

If there is a way, let me know please.

If there is no a current way, it would be convenient perhaps to include it in the dic-parameters. As it is a parameter that might throw some Cuda errors if it is not set properly.

Regards,
Giuliano.

**Comment by gmaggi** [comment]
Thanks for the note @alejoe91 !
Another remark, this time is about KiloSort(1).

It seems to me that Nfilt can not be passed to the params in https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort/kilosort.py#L30

If there is a way, let me know please.

If there is no a current way, it would be convenient perhaps to include it in the dic-parameters. As it is a parameter that might throw some Cuda errors if it is not set properly.

Regards,
Giuliano.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/121
