### ISSUE TITLE
implement YASS

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikesorters#11]

**Comment by samuelgarcia** [comment]
JinHyung Peter Lee said me that they went to finish some implementation in yass and then they will work on the implemenattion themself here.

**Comment by alejoe91** [comment]
Yes I made an issue on the YASS page :) https://github.com/paninski-lab/yass/issues/288

**Comment by alejoe91** [comment]
Hi @jinhyunglee 

Any update on this? :)

**Comment by jinhyunglee** [comment]
Hi Alessio,
sorry for the delay. 
There are few more updates coming for yass but I think we are in a good shape for sharing it.

One problem is that yass evolved too much and now it requires gpu and cuda to run. 
Do you think it is okay?

**Comment by alejoe91** [comment]
Hi @jinhyunglee 

That's totally fine! We are updating the docs now so it's the perfect time to have an install guide for all sorters.

**Comment by bendichter** [comment]
Any plans to integrate this?
