### ISSUE TITLE
run_mountainsort4() ValueError

### ISSUE THREAD

**Issue by BMT01** [SpikeInterface/spikesorters#118]
Hello -

I have `ml_ms4alg`, `mountainlab_pytools`, `spikeextractors version 0.7.3` and `spikessorters version 0.2.5` installed.

I have multiple 3 channel x Nsample recordings I'd like to sort with mountainsort4. I am able to successfully load the recording with `MdaRecordingExtractor()` - all timeseries and parameters are successfully passed.

When I run `spikesorters.run_mountainsort4(recording)`, I receive errors such as the following: `*** ValueError: cannot reshape array of size 69264 into shape (3,30000)`.

However, if i run `ml_ms4alg.mountainsort4(recording=recording, detect_sign=-1)`, sorting completes successfully.

Not sure how to debug this issue, but I would like to run this all within the SpikeInterface ecosystem. Any help would be greatly appreciated, thanks.

**Comment by BMT01** [comment]
as an update, I got this output from running `spikesorters.run_mountainsort4(recording, verbose=True)`:

```Using 6 workers.
Using tmpdir: /tmp/tmpfbs511p_
Num. workers = 6
Preparing /tmp/tmpfbs511p_/timeseries.hdf5...
Cleaning tmpdir:: /tmp/tmpfbs511p_
ValueError: cannot reshape array of size 69264 into shape (3,30000)

**Comment by alejoe91** [comment]
Hi @BMT01 

I think this migh be due to a wrong 'extraction' of the data. Is the original file format an mda folder?

If you load the data as: `rec = se.MdaRecordingExtractor('your-mda-folder')`, what is the output of:
```
print(rec.get_num_channels(), rec.get_num_frames(), rec.get_traces().shape)
```
?

You can also check if the signals look right with spikewidgets:
```
import spikewidgets as sw

sw.plot_timeseries(rec)
```

**Comment by BMT01** [comment]
Yes, the directory is an mda folder (raw.mda, params.json, geom.csv).

The output of the commands you suggested are correct:
`d3 36683088 (3, 36683088)`

The output looks good too:
![Screenshot from 2020-03-15 14-36-19](https://user-images.githubusercontent.com/29519133/76708057-e2677480-66eb-11ea-94e3-6f7064bc8c56.png)

**Comment by alejoe91** [comment]
Wow that is really strange. Would you mind sending me the mda folder in a zip? Are you using the latest version of ml_ms4alg?

Thanks again for bringing this up! Maybe @magland has some clues as well

**Comment by alejoe91** [comment]
what version of `spiketoolkit` do you have? 
Can you try the following:
```
sort = ss.run_mountainsort4(rec, filter=True)
sort = ss.run_mountainsort4(rec, filter=False)
sort = ss.run_mountainsort4(rec, filter=False, whiten=False)
```
It might be a problem of whitening without filtering (note that filtering is not enabled by default for MS4)

**Comment by BMT01** [comment]
Hello -

My version of `spiketoolkit` is `0.5.2` and `ml_ms4alg` is `0.3.2`.

`ss.run_mountainsort4(rec, filter=True)` ran without any errors, `ss.run_mountainsort4(rec, filter=False)` produced the same error,
`ss.run_mountainsort4(rec, filter=False, whiten=False)` also ran without any errors.

So that idea (whitening without filtering producing the error) makes sense. I tried to set `filter=True` in `params.json`, does that not get passed? Or do I have to manually pass these parameters to the sorter?

**Comment by alejoe91** [comment]
You can pass parameters as arguments to the `run` function. You can get the parameters as a dictionary for each sorter as: `params = ss.get_default_params('sorter-name')` (e.g. 'mountainsort4').
Then you can change the parameters that you want (e.g. `params['filter'] = True`) and pass it back to the run function with: `sort = ss.run_mountainsort4(rec, **params)`.

Note that the `params.json` is unrelated to spike sorting, but it's only for loading the recording (with metadata as sampling frequency etc.).

Hope this is clearer :) and thanks for the support!

**Comment by BMT01** [comment]
Ah, that's much clearer. Thanks!
