### ISSUE TITLE
nfilter_factor parameter for Kilosort2

### ISSUE THREAD

**Issue by MarineChap** [SpikeInterface/spikesorters#120]
Dear, 
There is a reason that the nfilter_factor for Kilosort2 is fixed ? 
One of my postdoc colleague would like to change it. Do you think it could be possible to expose it? 

Thanks ! 
Marine

**Comment by alejoe91** [comment]
Hi @MarineChap 

No particular reason! I will expose it and make a PR. 
Is it called `ops.nfilter_factor`?

Cheers
Alessio

**Comment by alejoe91** [comment]
@MarineChap 

https://github.com/SpikeInterface/spikesorters/pull/121

**Comment by MarineChap** [comment]
That's was very fast! Thanks a lot !

**Comment by alejoe91** [comment]
I'll merge in 2 minutes! As soon as tests pass

**Comment by MarineChap** [comment]
Ah yes! Sorry ! Don't worry, the issue mentioned upper it is for just for the software engineer taking care of our cluster.
