### ISSUE TITLE
implement Wave_clus

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikesorters#13]

**Comment by ferchaure** [comment]
I was reading the kilosort wrapper, did you check that making a matlab script and then run it is better that use the matlab engine api for python? Just asking if you thought on the pros and cons

**Comment by samuelgarcia** [comment]
I think no.
Code generation and parameters is a quite easy to make and read so people not familiar with python should be able to patch if there are mistake.

The main drawback with the actual implementation is error handling.

**Comment by magland** [comment]
Regarding error handling, I think we should update the matlab sorter wrappers to use the following kind of code that we use in spikeforest that makes it possible to catch matlab exceptions and to have the code more readable. It makes use of a ShellScript class there. Still not perfect...

```
print('Running ironclust in {tmpdir}...'.format(tmpdir=tmpdir))
    cmd = '''
        addpath('{source_dir}');
        addpath('{ironclust_path}', '{ironclust_path}/matlab', '{ironclust_path}/matlab/mdaio');
        try
            p_ironclust('{tmpdir}', '{dataset_dir}/raw.mda', '{dataset_dir}/geom.csv', '', '', '{tmpdir}/firings.mda', '{dataset_dir}/argfile.txt');
        catch
            fprintf('----------------------------------------');
            fprintf(lasterr());
            quit(1);
        end
        quit(0);
    '''
    cmd = cmd.format(ironclust_path=ironclust_path, tmpdir=tmpdir, dataset_dir=dataset_dir, source_dir=source_dir)

    matlab_cmd = mlpr.ShellScript(cmd, script_path=tmpdir + '/run_ironclust.m', keep_temp_files=True)
    matlab_cmd.write()

    shell_cmd = '''
        #!/bin/bash
        cd {tmpdir}
        matlab -nosplash -nodisplay -r run_ironclust
    '''.format(tmpdir=tmpdir)
    shell_cmd = mlpr.ShellScript(shell_cmd, script_path=tmpdir + '/run_ironclust.sh', keep_temp_files=True)
    shell_cmd.write(tmpdir + '/run_ironclust.sh')
    shell_cmd.start()

    retcode = shell_cmd.wait()

    if retcode != 0:
        raise Exception('ironclust returned a non-zero exit code')
```

**Comment by samuelgarcia** [comment]
Ironclust have a CLI ?

**Comment by magland** [comment]
> Ironclust have a CLI ?

What do you mean @samuelgarcia ?

**Comment by samuelgarcia** [comment]
a command line interface p_ironclust is command in the console ?
I thought it was run into matlab directly.

**Comment by magland** [comment]
If you look more closely at he code you will see that p_ironclust is being called inside matlab.

**Comment by samuelgarcia** [comment]
Oups sorry. yes.
I am too tired, the weatheris super hot in france and I slept only a few hours :(

**Comment by magland** [comment]
> I am too tired, the weatheris super hot in france and I slept only a few hours :(

Hope you can catch up on sleep. Sometimes it's hard for me to adjust after travel. But sleep is important.

**Comment by alejoe91** [comment]
@ferchaure any update on this? Let us know if you need help. We can port the spikeforest version to start with. What do you think?

**Comment by ferchaure** [comment]
> We can port the spikeforest version to start with. What do you think?

Yes, that will be nice, I think that port is good enough.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/53

**Comment by ferchaure** [comment]
Hi @alejoe91 I have been using Wave_clus and spikeinterface, Do you think that I should add a parameter in Wave_clus to disable the filters that are always applied to the signal?

**Comment by alejoe91** [comment]
Hi @ferchaure 

Personally I like to filter and do some preprocessing before spike sorting, so I think it's a very good idea! Can you make a PR?

**Comment by ferchaure** [comment]
ok, I will make a PR soon. It is just a change on the default parameters of the spikeinterface wrapper, disabling the filters. But I would like to maintain the idea of using 2 different filters in the signal: one for detection and another one for sorting (I saw a few cases where that was quite useful). Do you think that adding more parameters (the parameters of the optional filters) to the wrapper will be a good idea?

**Comment by alejoe91** [comment]
No problem at all in adding useful params :)

**Comment by ferchaure** [comment]
Hi again @alejoe91 
I was looking the changes you [asked for](https://github.com/SpikeInterface/spikeextractors/pull/393), and I found ([here](https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/waveclus/waveclus.py#L94)) that the recording is written on a mda file, then loaded and saved on a mat file. am I right?
Is it possible to use scipy.io.savemat to save the recordings directly as Matlab files?

**Comment by alejoe91** [comment]
Hi @ferchaure 

Sure you can use script if you think it's better. The mda format is a straight binary with a small header, so writing and reading should be quite efficient! Can you test if using scipy.io is as efficient?

**Comment by ferchaure** [comment]
I know but create the mda file is not required, I can create the mat files directly on python. I did a little test with a simulated recording. 

Using savemat the mat files are created in 0.26 seconds.
But using the mda as the intermediary between python and matlab takes 1.3 seconds (0.72 creating the mda on python and 0.58 loading the file in matlab and saving the mat files).

The python script is [here](https://gist.github.com/ferchaure/a6979aa2db34b4346ec49baa26225832) and the matlab [here](https://gist.github.com/ferchaure/03712954118f1adfbe3d90315888b094)

**Comment by alejoe91** [comment]
Great! Then I have nothing against saving directly to mat file :)

**Comment by Aleman-Z** [comment]
Hey guys, I am doing sorting with Waveclus in some large concatenated recordings and realized that using **scipy.io.savemat** as suggested by @ferchaure can be an issue since it has a limit of 4GB as explained here [http://scipy-user.10969.n7.nabble.com/SciPy-User-Maximum-file-size-for-savemat-td18583.html](url) 

I get this error when trying to use savemat: 
_scipy.io.matlab.miobase.MatWriteError: Matrix too large to save with Matlab 5 format_

So maybe you could consider going back to mda? I read others have also worked around this by using HDF5 but I am not sure which would be the best and fastest option.

**Comment by alejoe91** [comment]
HI @Aleman-Z 

@ferchaure what do you think? We can either switch back to mda or use h5py to save and load larger mat files

**Comment by samuelgarcia** [comment]
Maybe we can switch to another package for mayt file
pymatreader
mat4py
I never try then but the scipy.io.loadmayt is pretty old.

**Comment by ferchaure** [comment]
Writing the recording on disk an extra time just to change the format is less than optimal. I think we have three options:

1. Use some package like hdf5storage (or the ones proposed by samuel) to save the recording in an up-to-date .mat file.
2. Save the recording in a basic hdf5 (similar to what I did for combinato) and code in WaveClus a way to open hdf5 files
3. Use the MATLAB Engine API to pass numpy vectors directly to Matlab and save the .mat files natively. 

Option **1**  will help all Matlab sorters. But you have to choose the library
By the other hand, **2** could be a fast patch for WaveClus. I could add a pull-request in a few weeks. And maybe you can add on the docs a recommendation for Matlab sorters about reading at least h5 files.
Finally, I think that **3** have a lot of potential but it will require more code and user configuration.
