### ISSUE TITLE
Invalid klusta batch script

### ISSUE THREAD

**Issue by TRuikes** [SpikeInterface/spikesorters#137]
When running 
```
# Get default klusta params
klusta_params = ss.get_default_params('klusta')
sorting_klusta = ss.run_klusta(recording=rec,
                               output_folder=filepath + r'\klusta',
                               verbose=True,
                               **klusta_params)
```
It properly generates a klusta folder, but the executable is named `klusta.bat`. Then when calling klusta (`klusta myparams.prm`) it will execute the batfile instead.

Fixable by giving the `klusta.bat` another name (`run_klusta.bat`)

**Comment by alejoe91** [comment]
Hi @TRuikes 
Will fix this asap :)
Cheers
Alessio

**Comment by TRuikes** [comment]
thx

**Comment by alejoe91** [comment]
should be fixed here https://github.com/SpikeInterface/spikesorters/pull/138
