### ISSUE TITLE
update IronClust wrapper form SpikeForest 

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikesorters#14]
The current IronClust wrapper is outdated. 

We should merge with the one from SpikeForest (https://github.com/flatironinstitute/spikeforest/tree/master/spikeforest/spikesorters/ironclust)

**Comment by magland** [comment]
I can help with this. I will assign to myself.

**Comment by samuelgarcia** [comment]
Supper cool. Thanks Jeremy.

**Comment by samuelgarcia** [comment]
This is done is #32.
Can we close ?

**Comment by magland** [comment]
Yes. Closing.
