### ISSUE TITLE
Path to wave clus Sorting Output Incorrect 

### ISSUE THREAD

**Issue by Bilalgp** [SpikeInterface/spikesorters#141]
I am trying to run the spikewidgets function plot_unit_waveforms() from sorted data using wave_clus. I noticed the path in the function is different than what the spikesorters outputs. I'll try to find where path is defined and change it but I thought I should let you know.

![image](https://user-images.githubusercontent.com/26805330/81495177-5782a080-927c-11ea-9e1b-646e3da77007.png)
![image](https://user-images.githubusercontent.com/26805330/81495179-59e4fa80-927c-11ea-889b-2db1a2043fac.png)

**Comment by alejoe91** [comment]
Hi,

From the two screenshot isn't the path the same?

**Comment by Bilalgp** [comment]
Yes. Apologies for not being clear. I think I misunderstood what happened. I think the plot_unit_waveforms() function requires the folder to exist (not delete_output_folder = True) and I was confusing the error with another file in another file.  Thank you.

**Comment by Bilalgp** [comment]
Actually, I am not sure why but another issue started again. I am running the spike tutorial code, where I am running the run_waveclus() function with grouping_property = 'group'.  When trying to run plot_unit_waveforms() in the spikewidget class saying I am getting an error of an invalid argument of a tmp file.

When running, export_to_phy in the spiketoolkit class I am getting an error of recording_f not having an attribute 'itemsize'. This goes away if I use the unfiltered recording but I wanted to practice exporting the filtered recording, recording_f.

 I am not sure how to troubleshoot. 

![image](https://user-images.githubusercontent.com/26805330/81506502-b9ff8f00-92c4-11ea-9f8d-4d08d7587fdc.png)

![image](https://user-images.githubusercontent.com/26805330/81506504-be2bac80-92c4-11ea-9af7-6fe755d8ff69.png)

![image](https://user-images.githubusercontent.com/26805330/81506507-c1269d00-92c4-11ea-9f2e-5427939871d1.png)


![image](https://user-images.githubusercontent.com/26805330/81506535-ff23c100-92c4-11ea-9ec4-46c329cd6005.png)

**Comment by alejoe91** [comment]
Hi,

For the first error I suspect you have a spiketrains with size 0, which numpy doesn't like.. we should check and filter out those spiketrains. I'll look into it tomorrow.

The second error is due to the fact that the dtype is a str and not a numpy array. I'll fix that as well tomorrow :)

**Comment by alejoe91** [comment]
Could you send me the full notebook and a link to the data you are using?

**Comment by Bilalgp** [comment]
Here is my notebook. I was following the tutorial and the four-tetrodes recording data from the tutorial. I was running the code using wave_clus. I don't see any spiketrains with zero in the rasterplot, but just in case I missed something, would you recommend using a manual function like filter(None, sorters) to remove any empty arrays? 

[SpikeInterface_Tutorial.zip](https://github.com/SpikeInterface/spikesorters/files/4608651/SpikeInterface_Tutorial.zip)

**Comment by alejoe91** [comment]
Ok, I'll try to reproduce the issue on my machine.

Note that I just updated all packages! Maybe that fixes the issues. Can you try `pip install --upgrade` for all packages?

**Comment by Bilalgp** [comment]
You mean upgrade all packages except the spikeinterface master correct (from this thread https://github.com/SpikeInterface/spikesorters/issues/140) 

Or should I upgrade spikeinterface?

**Comment by alejoe91** [comment]
Correct! spikeinterface is not a real package, it's just a wrapper for the other packages

**Comment by Bilalgp** [comment]
Thank you. The plot_unit_waveforms() function works.  Out of curiosity, if there were empty spike trains would you recommend using a manual function to remove the empty arrays? Also, is the output for the plot_unit_waveforms() function look like this because of the resolution issues of the widget tool? 

![image](https://user-images.githubusercontent.com/26805330/81556403-3d1df500-9358-11ea-8586-47d6c8ea1d39.png)

I am receiving a few errors with the phy output. First time I execute I receive this error, followed by an invalid argument error if I try running it again. 

![image](https://user-images.githubusercontent.com/26805330/81556756-db11bf80-9358-11ea-942e-756c30474dbc.png)

![image](https://user-images.githubusercontent.com/26805330/81556861-07c5d700-9359-11ea-818f-99230fc8f382.png)

**Comment by alejoe91** [comment]
@Bilalgp can you try to plot 1 unit only? You can use the `unit_ids = [0]`.

It might be due to the fact that electrodes are very far from each other. 
I'll try to reproduce the second issue from your folder and get back to you

**Comment by alejoe91** [comment]
@Bilalgp it works on my side.

Can you try to rerun the export_to_phy command as follows?

```
recording_cache = se.CacheRecordingExtractor(recording_f)
st.postprocessing.export_to_phy(recording_cache, sorting_waveclud_all, 
                                                        output_folder='phy_waveclus_all', grouping_property='group', 
                                                        recompute_info=True)
```

Teh caching mechanism will speed up the extraction of waveforms. Otherwise, for each waveform snippet, the filter is run on-the-fly.

Let mw know if you get the same issue this way

**Comment by Bilalgp** [comment]
Thank you for the prompt response. This is what I get when I try the 1 unit. I am not sure why the data trace looks like this. Do I need to manually change the acquisition rate for wave_clus in MATLAB? 

![image](https://user-images.githubusercontent.com/26805330/81592880-9d2e8e80-938c-11ea-9a15-8bb2203ce20d.png)

The export_to_phy command works thanks! I just get the cacherecordingextractor warning. 

![image](https://user-images.githubusercontent.com/26805330/81593091-ee3e8280-938c-11ea-9317-db47311f3a08.png)

**Comment by Bilalgp** [comment]
Do you have a recommended way to export the spike sorting results to a file and import it so that I won't need to continuously run the code? 

Also, is there a way to import the results from Wave_clus in MATLAB directly to SpikeInterface? Or if not, your best approach to how I should go about doing so? I think that would help me with the analysis since I am new SpikeInterface.

**Comment by alejoe91** [comment]
Hi @Bilalgp 

I think that the waveform looks good, you just need to adjust height and width.

To save the result you can use the caching/dumping mechanism:

```
recording_cache = se.CacheRecordingExtractor(recording_f)
recording_cache.save_to_file('path-you-decide/recording.dat')
recording_cache.dump_to_pickle('path-you-decide/recording.pkl')
```

You can do the same for the sorting object. Note that thi will also dump all waveforms, templates, etc.

To load them back you can simply do:

```
recording = se.load_extractor_from_pickle('path-you-decide/recording.pkl')
sorting = se.load_extractor_from_pickle('path-you-decide/sorting.pkl')
```

Alternatively you can also save the data to NWB qith the `NWBRecordingExtractor.write_recording()` and `NWBSortingExtractor.write_sorting()`

**Comment by Bilalgp** [comment]
Thank you for the response. I am not really understanding the output of the plot_unit_waveforms. Isn't the output supposed to be plotting the same waveform? I looked at the API for SpikeInterface, but is there some further documentation where I can learn more about this and how to change the height/width?  

For the NWB, just to clarify, this could be potentially also be used to save a MATLAB wave_clus output and imported into SpikeInterface? Would the documentation of NWB on github be the best place to learn more about making a data file output? https://github.com/NeurodataWithoutBorders/matnwb 

I am receiving a permissions error when executing the save_to_file function. I think it might be something specific to Windows.

![image](https://user-images.githubusercontent.com/26805330/81663304-947d9d00-940c-11ea-970c-8fe38b9ec01c.png)

**Comment by alejoe91** [comment]
Yes it is plotting 1 waveform, but on all channels. In order to change the wiidth and heigth you can use `%matplitlib notebook` in and just change it manually. Alternatively you can access the widget figure as `w.figure`. They are matplotlib objects.

You cannot import the mat files from waveclus in SpikeInterface directly. Only the spike trains are saved and loaded. what kind of data do you want to load from the MATLAB output?

Windows can be problematic with those permission errors. For each extractor, you can set a temporary folder of your choice, e.g. `recording.set_tmp_folder('path-to-your-folder')`. Then the caching will take place there.

**Comment by Bilalgp** [comment]
The way I understand wave_clus is from the GUI from where it is used and where it plots spikes per channel independently. I may be misunderstanding something, but I don't understand how this can make having 1 waveform on all channels possible. For starting with SpikeInterface,

I was thinking it might be easier to use the output of wave_clus in MATLAB, which is a .mat file, and convert it to something SpikeInterface can use. For this route, the validation metrics in SpikeInterface would be the most useful.

**Comment by alejoe91** [comment]
> The way I understand wave_clus is from the GUI from where it is used and where it plots spikes per channel or tetrode independently. I may be misunderstanding something, but I don't understand how this can make having 1 waveform on all channels possible.
> 

Waveforms are just snippets of recordings extracted around the spike times. In this case there are in total 16 channels, and the waveforms are extracted from all channels. If you want to plot less channels, you can use the `max_channels=4` in `plot_unit_waveforms`.



> For starting with SpikeInterface, I was thinking it might be easier to use the output of wave_clus in MATLAB, which is a .mat file, and convert it to something SpikeInterface can use. For this route, the validation metrics in SpikeInterface would be the most useful.

By running wave_clus sit SI, we already convert the info that we need (spike times and unit ids) to a SpikeInterface readable format. Then you can use SI to compute metrics. I don't understand what you are missing from wave_clus.

**Comment by Bilalgp** [comment]
> By running wave_clus with SI, we already convert the info that we need (spike times and unit ids) to a SpikeInterface readable format. Then you can use SI to compute metrics. I don't understand what you are missing from wave_clus.

I was more going towards if I manually curate/adjust the sorted waveforms using the wave_clus GUI then it would be easier to import into SpikeInterface rather than curating from SpikeInterface.

**Comment by alejoe91** [comment]
I see what you mean! You can open an issue on the wave-clus repo and ask if they can add a function to export in an SI readable format. Alternatively, they could also write an Extractor in spikeextractors to read the wave-clus files.

We recommend using Phy for manual curation. Have you tried that?

**Comment by Bilalgp** [comment]
I see. Thank you. I haven't used Phy before but I will try to use that as well for curation.

**Comment by Bilalgp** [comment]
If I end up needing to do create the extractor myself, do you have a recommended source on how the extractor should be set up? Is there something on the API that would be the best place to start? The outputs of wave_clus are relatively few so it should be easy if I know where/what to set.

**Comment by alejoe91** [comment]
https://spikeinterface.readthedocs.io/en/latest/sorting_extractor.html :)

**Comment by Bilalgp** [comment]
Thank you.
