### ISSUE TITLE
Question about unsorted spikes

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spikesorters#149]
Hi, I'm trying to improve a project using SpikeInterface, but I would need the times of the unsorted spikes? Is this possible? 
In wave_clus we have that times as the cluster 0 but we don't give that info to the SpikeInterface wrapper.

**Comment by samuelgarcia** [comment]
Hi Fernando.
At the moment, spikeextractor don't have this feature but it would easy to add it.

I think the best is to add a method for this like:
```SortingExtractor.get_unsorted_spike_train(self)```
or this but I think it would be too complicated for some extactor.
```SortingExtractor.get_units_spike_train(self, unit_ids="bad")```

In tridesclous the non sorted have a -1 label. I don't think it is a good idea to decide at spikeinterface level which label represent the unsorted.

**Comment by alejoe91** [comment]
Hi Fernando,

I think that the best way would be to add a `keep_unsorted` argument to the `WaveClusSortingExtractor`. When that is True, you can load the unsorted psikes in an extra spike train, and I would also add a `property` to the unit indicating whether it is `sorted` or `unsorted`. 

See how it's done in a similar way for `good` units in KS2 [here](https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/kilosortextractors/kilosortextractors.py#L24) / note that in this case properties are already loaded by the `PhySortingExtractor`, from which the class is derived.

**Comment by samuelgarcia** [comment]
Alessio, I think "unsorted" is a bit differents than "good" or "bad" from KS.
"unsorted" is that you known it is unsorted.

About putting this info as property is also an option we we must standadize accros extractor how to do it : the name and the value of the property has to be define.
A method on top of that would force the convention.

**Comment by alejoe91** [comment]
@samuelgarcia I think this is a very special case and I wouldn't modify the API when we can use properties. I don't know if we need a convention for this. @ferchaure what do you think?

**Comment by ferchaure** [comment]
I strongly agree with this:
> I think "unsorted" is a bit different than "good" or "bad" from KS.
"unsorted" is that you known it is unsorted.

I like the `SortingExtractor.get_unsorted_spike_train(self)` idea. Principally because calling that detections 'units' doesn't feel right. I understand that using properties can be more manageable for the API, but a lot of people will use mainly `get_unit_ids` and `get_unit_spike_train` to use the sorting and I guess that including a unit just with noise and artefacts will generate confusion. 

In any case, I will be happy if that info is available. I will use it for something quite trivial, but a lot of things can be improved using the unsorted events (like: adjust sorting parameters, check the recording stability, find annoying artefacts).

**Comment by alejoe91** [comment]
Ok then, you convinced me!

@ferchaure would you have time to implement this? I think that WaveClus would be the first extractor for this feature :) 

I would add the method in the `SortingExtractor` class, that raises a `NotImplementedError` by default. Then derived extractors can override it

**Comment by ferchaure** [comment]
Ok, I will do it. I'm currently improving the extractor, adding more parameters, etc
