### ISSUE TITLE
prm file not included in pypi package

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikesorters#15]
I get the following error when running klusta from the pypi-installed spikesorters package

>> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/spikesorters/klusta/config_default.prm'

I think we need to ensure the .prm files are added to the package

**Comment by magland** [comment]
I made PR for this (just fixing paths in MANIFEST.in). Please merge and cut a new release as soon as you can so that I can use this in spikeforest.

https://github.com/SpikeInterface/spikesorters/pull/16

**Comment by alejoe91** [comment]
merged

**Comment by samuelgarcia** [comment]
@alejoe91 : can you tag a new release ?
