### ISSUE TITLE
Kilosort2 kcoords are the same

### ISSUE THREAD

**Issue by manimoh** [SpikeInterface/spikesorters#150]
Hi,
I was trying to use the spikesorters pipeline to run Kilosort2 on ephys data collected via a 4- shank, 32-channel sillicon probe.

The option 'kcoords' in Kilosort2 is used to separate channel groups into shanks or different tetrodes for the purpose of restricting templates to the channels in the same channel group. 
See [this](https://github.com/MouseLand/Kilosort2/blob/1450e72237e019a1eddfeeeb022dfc9d49880e46/configFiles/createChannelMapFile.m#L34-L46) for details.
However  in the kilosort2.py implementation, the kcoords are all set to be the same.  https://github.com/SpikeInterface/spikesorters/blob/d6f6b77ad3fd93291192e1452b904e5db7e7d664/spikesorters/kilosort2/kilosort2.py#L95
https://github.com/SpikeInterface/spikesorters/blob/d6f6b77ad3fd93291192e1452b904e5db7e7d664/spikesorters/kilosort2/kilosort2.py#L155

Shouldn't the kcoords variable be set from the channel groups so that it gets passed onto the KS2 MATLAB subroutine properly?

**Comment by alejoe91** [comment]
Hi! 

You have to use the argument grouping_property='group' to spike sort by group. We decided to handle groups externally, since we have tools to split and merge recording and sorting output :) and the can be run in parallel.

Cheers
Alessio

**Comment by manimoh** [comment]
That was helpful. Thanks @alejoe91 
However, kilosort2 seems to have a more flexible usage of the parameter **kcoords** than just using it to define channel groups. See [this](https://github.com/MouseLand/Kilosort2/blob/1450e72237e019a1eddfeeeb022dfc9d49880e46/configFiles/createChannelMapFile.m#L34-L46) for details.
But for that usage another parameter, **ops.criterionNoiseChannels** (description in the link above) needs to be exposed and changed by the user.

**Comment by manimoh** [comment]
On a related note, I am actually not sure if Kilosort2 has actually implemented the **kcoords** feature in its present form. See [this](https://github.com/MouseLand/Kilosort2/issues/155)

**Comment by alejoe91** [comment]
Yes I think I had looked into it before, thanks for checking! I think it's better to handle grouping outside, even because any property 
 can be used for grouping. Can I close the issue?

**Comment by manimoh** [comment]
Sure, go ahead and close it!
I agree with you about it being a better design decision to handle grouping outside of a specific sorting algorithm, but when and if KS2 does implement the **kcoords** feature the way they mention it, not passing this group information will not allow KS2 to work as intended.
