### ISSUE TITLE
Kilosort2 log is present only in Matlab console

### ISSUE THREAD

**Issue by manimoh** [SpikeInterface/spikesorters#151]
On running Kilosort2 via spikeinterfaces, the kilosort2 log is displayed only on the console of the launched Matlab instance which closes upon successful execution or an error. Ideally, this console output should be saved in a "matlab-log-file" so that if the Kilosort2 throws an error (and NOT the spikeinterface/spikesorters pipeline), users can look at it.
Based on [this](https://www.mathworks.com/matlabcentral/answers/102082-how-do-i-call-matlab-from-the-dos-prompt#answer_419655), a minor modification to the shell command in https://github.com/SpikeInterface/spikesorters/blob/d6f6b77ad3fd93291192e1452b904e5db7e7d664/spikesorters/kilosort2/kilosort2.py#L170-L180
to 
`matlab -nosplash -nodisplay -wait -r kilosort2_master -logfile matlab_console_log.txt`
makes a log file with the entire MATLAB console output in the working directory.
I tested this on machines with Windows10/MATLAB 2019b and Ubuntu18.04/MATLAB 2020a, and it works there perfectly.
In theory, this could be done for all MATLAB based sorters.

**Comment by alejoe91** [comment]
Hi @manimoh 

Sure that sounds like a good idea. If you pass the log file, does the output get printed in the console as well? I think it would be nice to have both!

I think it would be better to implement this in the [ShellScript](https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/utils/shellscript.py) class, which handles all calls to bash scripts (including matlab). In that case, also the output from non-matlab sorters could be saved in a log file.

Would you have time to look into this?

**Comment by manimoh** [comment]
Hi @alejoe91,
To display it in the terminal console, one must pass `-log` along with the rest of the shell command. I agree with you that making that change via the ShellScript class would be a better way to do it.
And I can look into this and will make a PR soon!

**Comment by manimoh** [comment]
Also, do we want the log to be displayed on the terminal as well as copied to a log file, or do we want it only to be dumped into a log file?

**Comment by manimoh** [comment]
Adding the Pull request here:
#156

**Comment by manimoh** [comment]
Resolved in merged PR#156
