### ISSUE TITLE
Kilosort2 json dump shows inconsistent properties

### ISSUE THREAD

**Issue by manimoh** [SpikeInterface/spikesorters#152]
Hi,
I was using spikeinterfaces to run Kilosort2 on continously sampled wideband data collected via a Neuralynx Acquisition system and this is the barebones schematic of steps that I followed (see https://github.com/vandermeerlab/data-formats/blob/master/ks2_30kHz_continuous.ipynb for the full workflow) :
1) Extract recordings from the folder using NeuralynxRecording Extractor and put them into a list of various segments
`sample_file = 'D:\M40\M40-2020-04-29-CDOD12\CSC1.ncs'`
`dname = (op.dirname(sample_file))`
`reader = neo.NeuralynxIO(dirname=dname)`
`recordingList = [se.NeuralynxRecordingExtractor(dirname=op.dirname(sample_file), seg_index=i) for i in range(reader.segment_count(0))]`
2) Pass this list onto a MultiRecordingTimeExtractor to concatenate the various segments:
`recordingFull = se.MultiRecordingTimeExtractor(recordingList)`
3) Manually set channel locations and channel groups
`# group_ids and channel_locs are arrays of appropriate lengths`
`recordingFull.set_channel_groups(group_ids)`
`recordingFull.set_channel_locations(channel_locs)`
4) Run Kilosort2 with appropriate parameters:
`ks2_out0 = ss.run_kilosort2(recordingFull, output_folder = 'C:/Users/mvdmlab/ss_ks2_test3', **ks2_params)`

The whole thing runs and generates output in the specified output location. However on inspecting the 'spikeinterface_params.json' (See [this](https://github.com/vandermeerlab/data-formats/blob/master/ks2_test/spikeinterface_params.json) for an example), I see that group and locations are present at 2 places: one under recording->kwargs->recordings[seg_index=0, block_index=0]->key_properties 
https://github.com/vandermeerlab/data-formats/blob/7c23f42e0934680fa12385739119f8704fda73d1/ks2_test/spikeinterface_params.json#L34-L179, 
and another recording->kwargs->key_properties
https://github.com/vandermeerlab/data-formats/blob/7c23f42e0934680fa12385739119f8704fda73d1/ks2_test/spikeinterface_params.json#L256-L403

As you can see the latter is the one with the correctly set values while the former one has the default values (values before setting them manually). The latter is being used to generate the kilosort2 config files and channel map, so the pipeline doesn't seem to be affected by it. 
I am not sure if this is a bug, or it is meant to be like that but I would think that the default properties should be located in a better place then nested under the first recording.

**Comment by alejoe91** [comment]
Hi @manimoh 

Thanks for the issue. Since you set the groups and locations on the recordingFull, they are saved as properties of the full recording (and propagated to the sorter). In this case the group and location info of the single segment are not used. If you set the groups and locations for each of the segment and then build the MultiRecordingExtractor, the properties should be propagated. In other words, I think that this is the correct behavior :)
The json file in fact is enough to re-instantiate the RecordingExtractor object.

**Comment by manimoh** [comment]
Thank you for explaining this!
Closing this now.
