### ISSUE TITLE
Comments and Questions about spikesorters

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spikesorters#154]
1- On windows machines, _-nodisplay_ is not an existing argument for Matlab. That argument is included in all the Matlab sorters, and it generates an unnecessary warning.

2- What do you think about the [MATLAB Engine API for Python](https://www.mathworks.com/help/matlab/matlab_external/get-started-with-matlab-engine-for-python.html)? using it makes possible to call Matlab commands directly from python applying always the same engine. That will reduce a lot the time opening Matlab running multiple recordings. I know that the current way to use Matlab sorters is the easy one (and it doesn't require user configurations), but maybe it can be a useful alternative.

3- This one is essentially for @samuelgarcia, is there a way to run tridesclous if the recording is already filtered? From the code of tridesclous it looks that the lowpass_freq (and/or highpass_freq)=None could be an option but at least from spikeinterface that doesn't work.

4- Is there another way to ask small questions other than the issues on the repositories? a slack, discord, gitter, riot or something like that? Probably in a few days, I will have more little questions about the different modules of spikeinterface and maybe you don't want a lot of small issues everywhere. I'm starting to focus more and more in a project that I really want to build on top of spikeinterface.

**Comment by samuelgarcia** [comment]
1. Could you make a PR that detect windows and remove this arg ?

2. Is it a free module in matlab ? If yes we could think about a double implementation : actual with 
   ShellScript + this new one if there is indeed a gain at startup.

3. In tridesclous, highpass_freq=None / lowpass_freq=None should remove the filtering steps. 
   Theses args are exposed. I don't understand. What error do you have ?

4. Personnaly, I like the github way even for small things. Forum like are less searchable for new 
    incomers.

**Comment by ferchaure** [comment]
1. The windows command is already in its own if statement. The change will only remove that word from the command string.

2. Yes is a free module, and probably it can help a lot. But a way to open the matlab engine in spikeinterface and keep that object alive across sorting should be implemented... Or maybe just allow it as a parameter for the run methods. Like: if the Matlab engine is an input, use it; otherwise, just open a new matlab of each run.

3. I got:
 `spikesorters.sorter_tools.SpikeSortingError: Spike sorting failed: lostfront_chunksize=None needs a highpass_freq
`  
Maybe because I'm using a single channel recording?

**Comment by samuelgarcia** [comment]
OK.
I now got the tridesclous error I will fix it.

**Comment by ferchaure** [comment]
(I continue the counting)
5 - Have you considered the case of long multi-files recordings? Do you think that spikeinterface will include a way to handle them?
6 - I notice than almost all the sorters are run using a bash script. This could allow us to include a line to change the Python virtual environment. I guess that installing the python sorters in its own environment could help with the dependencies. What do you think?

**Comment by samuelgarcia** [comment]
5.You can already use the MultiRecordingTimeExtractor to virtualy concatenate several recordings.
   A better approach would be that spiekextractors recordgins would handle explicitly the multi segment recording as neo do.
    We already talk about this. I will long propocess.
6. HS2, TDC and MS4 do not use script but use directly the python API. Yes indeed, moving theses sorter to script API would be 
    better to run then in several environement. It is a lot of work. If you really need env maybe you can use spikeforest that is build 
    on top of spikesorter but run every thing into docker so perfect and total isolation.

**Comment by ferchaure** [comment]
You answered all the questions and I have gitter for any new ones.
