### ISSUE TITLE
Pip install doesn't install from the current master

### ISSUE THREAD

**Issue by manimoh** [SpikeInterface/spikesorters#160]
I have noticed that pip install doesn't seem to be installing the contents of current master (for spikesorters, at least!). Is it intentional? If not, shouldn't every change to the master branch in the repos be accompanied by some increment in the version number so that pip installs gets the newest version?

**Comment by alejoe91** [comment]
Hi @manimoh 

We do not release after each PR (otherwise we would be at version 70000  on pip :) )
Once a few relevant changes are made, we make a new release. I think we will release all packages in maximum a week.

Cheers
Alessio
