### ISSUE TITLE
Both Ironclust and Waveclus returned a non-zero exit code

### ISSUE THREAD

**Issue by MingChingChiang** [SpikeInterface/spikesorters#162]
Hi, 
Thanks for this awesome tools again!
I was running the python-based sorters for a while and they currently run pretty stable.
When I try to run the Matlab-based sorters, such as Ironclust and Waveclus, I always get the error message:
(Ironclust) Waveclus returned a non-zero exit code
I've followed the NWB tutorial instructions setting path for the sorters
`ss.IronClustSorter.set_ironclust_path('/ironclust')`

load my data with probe file
`recording = se.BinDatRecordingExtractor('recording.dat', sampling_frequency=30000, numchan=32, dtype=np.int16)
  recording_prb = recording.load_probe_file('Cambridge_Probe_2X16.prb')`

bandpass filter, and common median refrencing
`recording_f = st.preprocessing.bandpass_filter(recording_prb, freq_min=300, freq_max=6000)
recording_cmr = st.preprocessing.common_reference(recording_f, reference='median', groups=[(np.arange(16)),(np.arange(16,32))])`

Before running the sorter I also change some default parameters
`default_IC_params['detect_sign'] = +1
default_IC_params['filter'] = False
default_IC_params['fGpu'] = False`

And run the sorter
`OUT_IC = 'tmp_IC'
sorting_IC = ss.run_ironclust(recording_sub_ch, **default_IC_params, output_folder=OUT_IC, verbose=False)`

The after several minutes I got 
  File "/spikesorters-0.3.3-py3.7.egg/spikesorters/ironclust/ironclust.py", line 179, in _run
    raise Exception('ironclust returned a non-zero exit code')
Exception: ironclust returned a non-zero exit code

Did I miss anything need to be set on the matlab side before I execute the matlab sorter?

Thanks for helping!

**Comment by alejoe91** [comment]
Hi @MingChingChiang 

Can you pull the latest version of spikesorters? We improved the logging mechanism so now you should see both in the console/jupyter the output of the sorters and that is also saved in a log file in the output folder. That should help to understand what's going on!

**Comment by MingChingChiang** [comment]
> Hi @MingChingChiang
> 
> Can you pull the latest version of spikesorters? We improved the logging mechanism so now you should see both in the console/jupyter the output of the sorters and that is also saved in a log file in the output folder. That should help to understand what's going on!

Sure! I'll do it now!

**Comment by alejoe91** [comment]
Set verbose=True!

**Comment by MingChingChiang** [comment]
@alejoe91 
Thanks for the suggestion! 
I check the log and it says the matlab command not found
Then I realize that I need to run the following code in the terminal
`export PATH=/Applications/MATLAB_R2019a.app/bin/:$PATH`
After this step I can run the matlab-based sorter, at least the ironclust is working!
Thanks a lot! 
Then I close this issue!
