### ISSUE TITLE
KiloSort2 not recognized as installed

### ISSUE THREAD

**Issue by TRuikes** [SpikeInterface/spikesorters#165]
[this line](https://github.com/SpikeInterface/spikesorters/blob/0a99a94f623241d85dc34b2478fa729ea7c63db2/spikesorters/kilosort2/kilosort2.py#L24) is checking for a file that doesn't exist (master_kilosort.m) on the [current KiloSort2 master](https://github.com/MouseLand/Kilosort2)

**Comment by alejoe91** [comment]
Hi @TRuikes 

The latest update checks for both master_kilosort.m and main_kilosort.m:

https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort2/kilosort2.py#L24

Should be fixed if you pull

**Comment by TRuikes** [comment]
ah =)
