### ISSUE TITLE
Can't install KiloSort2

### ISSUE THREAD

**Issue by TomBugnon** [SpikeInterface/spikesorters#166]
Hi!

I'm trying to install Kilosort2 but it doesn't appear in `installed_sorter_list`

I tried both methods:

- setting the environment variables by sourcing this file:
```bash
export IRONCLUST_PATH='/Volumes/scratch/neuropixels/matlab/external/ironclust'
export KILOSORT_PATH='/Volumes/scratch/neuropixels/matlab/external/KiloSort'
export KILOSORT2_PATH='/Volumes/scratch/neuropixels/matlab/external/Kilosort2'
```

- Running 
```python
import spikeinterface.sorters as ss
ss.Kilosort2Sorter.set_kilosort2_path('/Volumes/scratch/neuropixels/matlab/external/Kilosort2')
```

Note that the other sorters do appear:
```python
print(ss.installed_sorters())
```

> ['ironclust', 'kilosort']

I'm using spikesorters v0.3.3 on Ubuntu 20.04
Hope I'm not missing something silly 
Thanks! Tom

**Comment by alejoe91** [comment]
HI @TomBugnon 

I think this is related to this issue https://github.com/SpikeInterface/spikesorters/issues/165

Basically in kilosort2 repo the `master_kilosort.m` was changed to `main_kilosort.m`. In the master branch this is fixed: https://github.com/SpikeInterface/spikesorters/blob/0a99a94f623241d85dc34b2478fa729ea7c63db2/spikesorters/kilosort2/kilosort2.py#L24

If you install from source using the latest master Kilosort2 should magically appear :)

**Comment by TomBugnon** [comment]
oops I missed that issue. 

Thank you!
