### ISSUE TITLE
what kind of files can be removed after completing a sorting?

### ISSUE THREAD

**Issue by gmaggi** [SpikeInterface/spikesorters#167]
Hi,

When kilosort2@spikeinterface is executed, some files are created  as the 3 underlined in red in the attachment. 

- Are those files generated during the extraction? 
- can those files be removed once the calculation is completed?, or are those needed for the "manual refinement" with phy?

Thanks,
Giuliano.
![output of spikesort2](https://user-images.githubusercontent.com/11243913/88177464-33065580-cc29-11ea-81a7-6169e033418b.png)

**Comment by alejoe91** [comment]
HI @gmaggi 

So the `recording.dat` is created by SI and it's a binary copy of the recoridng. The `temp_wh.dat` is created by KS2 and used internally. The `recording` is somewhat odd and I've never seen it before. It's alsou outside of the `output_folder`, so I don't think it's SI-generated.

For Phy, I think you only need the `recording.dat` to visualize traces. Not 100% sure about the `temp_wh.dat`, but 90% sure that you can safely delete it. Maybe try to move it out of the folder and launch phy.

Cheers
Alessio
