### ISSUE TITLE
run_mountainsort never returns when run in parallel mode

### ISSUE THREAD

**Issue by jonnew** [SpikeInterface/spikesorters#168]
This may be an issue with mountainsort itself. However, when I run

``` python
params = ss.get_default_params('mountainsort4')
params['detect_threshold'] = 6
params['curation'] = False
params['parallel'] = True
params['grouping_property'] = 'group'
params['filter'] = False
params['verbose'] = True

sorting_MS4 = ss.run_mountainsort4(recording, **params)
```

spike sorting will run, and mountain sort will produce all of its appropriate output files (firings.mda etc). The output log prints

```
....etc ... etc ...

Done with ms4alg.
Cleaning tmpdir::::: /media/jon/Buffer/tmp/tmpnei60og7
Clustering for channel 4 (phase2)...Clustering for channel 3 (phase2)...

Clustering for channel 1 (phase2)...
Clustering for channel 2 (phase2)...
Found 1 clusters for channel 3 (phase2)...
Found 6 clusters for channel 4 (phase2)...
Found 1 clusters for channel 1 (phase2)...
Found 3 clusters for channel 2 (phase2)...
Preparing output...
Done with ms4alg.
Cleaning tmpdir::::: /media/jon/Buffer/tmp/tmp4zxt7zak
Clustering for channel 4 (phase2)...Clustering for channel 1 (phase2)...

Clustering for channel 2 (phase2)...
Clustering for channel 3 (phase2)...
Found 1 clusters for channel 4 (phase2)...
Found 1 clusters for channel 1 (phase2)...
Found 1 clusters for channel 2 (phase2)...
Found 2 clusters for channel 3 (phase2)...
Preparing output...
Done with ms4alg.
Cleaning tmpdir::::: /media/jon/Buffer/tmp/tmp7f514_9x
```

But the function never returns as `SortingExctractor` object. This only happens in parallel mode. It seems like spawned threads are not being joined and maybe deadlocked.

Potentially of consequence: internally, mountainsort uses `/tmp` to store what I imagine are mem mapped data object for each channel group run in parallel. My OS harddrive is not big enough to support these files, so I had to move the temp storate location to my ephys disk via

```python
# Alter the default /tmp directory which is used by mountain sort
_environ = dict(os.environ)
try:
    _environ['TEMPDIR'] = '/media/jon/Buffer/tmp'
finally:
    os.environ.clear()
    os.environ.update(_environ)
```

Not sure if maybe its creating a lock file in here and then e.g. looking for it in `/tmp`

**Comment by samuelgarcia** [comment]
Moutainsort is partially written in C++.
My guess that some part of code are not re entrant and so can not be run in parralel.
You should ask to Jeremy (@magland)

Try tridesclous ;)

**Comment by alejoe91** [comment]
Can you try to pull the latest spikesorters master? I think we fixed the parallel backend to make ms4 work

**Comment by samuelgarcia** [comment]
@alejoe91 : we did not release since the joblib parralell ?

**Comment by jonnew** [comment]
@samuelgarcia I'm interested in trying everything. Algorithmic-ally and performance wise, are they similar? I realize that this very package provides a means to compare them, but being incredibly lazy, I know ppl that use mountainsort to great effect for wire tetode probes which is what I use so I tend to listen to them :).

@alejoe91 Thanks I will try!

**Comment by samuelgarcia** [comment]
It was a joke.
Trying all sorters cost you one line of code in SI. (but also parameters search for your dataset).

**Comment by jonnew** [comment]
OK...

**Comment by alejoe91** [comment]
@jonnew for tetrodes I have been using KS2 and I was quite happy with it. With some automatic curation the output is also pretty clean

**Comment by jonnew** [comment]
Thanks @alejoe91, I will give it a try!

**Comment by jonnew** [comment]
@alejoe91 Update: when I try this with the latest, it runs to completion. I'm getting warnings about ABI incompatibility with the _bootstrap.py numpy library when I use the source version of the sorters library , but I think this is just unrelated python package hell issues.

Thanks for your help

**Comment by alejoe91** [comment]
@jonnew Happy to hear that! Closing the issue then :)
