### ISSUE TITLE
Any plans to implement Combinato?

### ISSUE THREAD

**Issue by seqasim** [SpikeInterface/spikesorters#169]
Combinato (https://github.com/jniediek/combinato) is a flavor of WaveClus that does a nice job of a) over-clustering, if you so desire, and b) chunking and parallelizing the unsupervised aspect of the clustering to dramatically speed up applications of SPC to large datasets.

**Comment by samuelgarcia** [comment]
Hi @seqasim. Yes it is a good idea.
Combinato appears to be written in python.
It should quite easy to do it.
Do you think you could do a PR for this ?
Have a look to other wrapper it is quite easy to make wrapper.

**Comment by seqasim** [comment]
Yes, I can definitely work on this! Wanted to make sure someone was not already

**Comment by seqasim** [comment]
Update: I am not working on this as it seems Combinato still runs into issues with different data formats and larger files that I can't quite figure out.
