### ISSUE TITLE
merging matlab sorters (spikeforest/spiketoolkit)

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikesorters#17]
I think merging of matlab sorters will be a bit more involved because I think some aspects of spikeforest handing is better. For example using ShellScript class for catching exceptions, etc. Also there are tricky details regarding auto-installs from github commits of the matlab projects. I think this is important because there is no package versioning like there is in python. The way sf handles it is pretty good right now.

Shall we set up a time next week to work on the merge of matlab sorters in a hangouts session?

@alejoe91 @colehurwitz @samuelgarcia

**Comment by colehurwitz** [comment]
I am free next week on every day except for Tuesday and Wednesday.

**Comment by magland** [comment]
Let's coordinate via email.

**Comment by samuelgarcia** [comment]
Yes.
I think we must keep the best implementation from ST or SF case by case.

At the moment to avoid depency of spikesorter on moutaintools we can have a copy of subset of tools like ShellScript inside spikesorters.
No ?

**Comment by magland** [comment]
Yes, and ShellScript is WIP, so we can make copies here there and
everywhere.

**Comment by alejoe91** [comment]
We can probably launch the CLI ones with the ShellScript as well

**Comment by magland** [comment]
Not to sound like Linus Torvalds, but I think both implementations of kilosort2 wrapper (spikeforest and spikeinterface/spikesorters) have serious problems. :)

Will take me some time to create what I consider a clean version by combining the best of both. But I think it will help.

**Comment by alejoe91** [comment]
@magland what do you think are the main problems?

**Comment by magland** [comment]
Actually, they are not too bad (shouldn't have said serious problems) - and they do seem to work. I just think that they both could be simplified a lot, and that makes it difficult to determine the differences and to merge them.

The spikeforest implementation has a convoluted way of getting the data into matlab (using mda format and argfile). I think this is because it was adapted from an older ironclust wrapper.

The spikeinterface implementation has confusing types. For example

```
if 'group' in recording.get_channel_property_names():
    groups = [recording.get_channel_property(ch, 'group') for ch in recording.get_channel_ids()]
else:
    groups = 'ones(1, Nchannels)'
```
In one case it is a list of integers. In the other it is a string. I guess I realize that it will be correct once it is embedded in the matlab code - but it's not so obvious. I guess that can be easily remedied.

The replacements in the txt files are not so intuitive because it's hard to match up what's being replaced. And I think there's a better way to do it. That can be remedied as well.

One difficulty is that the two implementations seem quite far apart even though they are presumably doing the same thing. If they end up giving different results, it will be hard to troubleshoot. That's why it might take a bit longer than I had hoped.

Maybe not too bad. I'll take a crack at it.

**Comment by magland** [comment]
Also would like to remove dependency on npy-matlab. (requires additional installation step)

**Comment by alejoe91** [comment]
we could save the output to MDA?

**Comment by magland** [comment]
working on it now. Saving to simple txt for now.

**Comment by samuelgarcia** [comment]
I think I prefer that the output of each sorter is the natural output of the sorter not a converted one.

For instance, the use case for me, is improving a sorter.
I want to re run many time (and sometimes only some steps of) a particular sorter. I do this outisde ST, in that the output is the "natural" output. For instance a tridesclous folder.

Converting to another format like mda or npz should be done at a upper level (like SF or the study module).

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/30

Kilosorts done. IronClust on ts way

**Comment by magland** [comment]
KS and KS2 seem to be working well in SF. Now working on IronClust wrapper.

**Comment by magland** [comment]
@alejoe91 @samuelgarcia 
I am unfortunately getting some different results between kilosort old and kilosort new wrappers... and in fact the new is crashing for all the synth_visapy recordings in SF. So I need to look carefully at the parameter files that are being used. (Fortunately I have scripts to replicate the failure)

**Comment by samuelgarcia** [comment]
I don't have yet a machine with a big GPU so I won't be able to help striaght now on KS.
Sorry.

**Comment by magland** [comment]
I found the problem is in the writing of int16 file in the case when the data are float (loss of precision). So for now this is what I am doing:

If the data are all integer, and in the proper range, just write to int16 as normal. Otherwise, scale first to be between +/- 2^14 and then write to int16.

See: https://github.com/SpikeInterface/spikesorters/blob/27a0034c7e99f69ad1ea933d0cdb8361dcd5e7aa/spikesorters/kilosort/kilosort.py#L181

```
def write_binary_int16_scale_if_needed(recording: se.RecordingExtractor, save_path: Path, time_axis: int=0):
    if save_path.suffix == '':
        # when suffix is already raw/bin/dat do not change it.
        save_path = save_path.parent / (save_path.name + '.dat')

    traces = recording.get_traces()
    min_val = np.min(traces)
    max_val = np.max(traces)
    if (min_val < -2**15) or (max_val >= 2**15) or (not _isinteger(traces)):
        print('Rescaling data before converting to int16.')
        max_abs = np.max(np.abs([min_val, max_val]))
        # scale with a margin
        scale_factor = 2**14 / max_abs
        traces = traces * scale_factor
    traces = traces.astype('int16')
    if time_axis == 0:
        traces = traces.T
    with save_path.open('wb') as f:
        traces.tofile(f)

    return save_path

def _isinteger(x): 
    return np.all(np.equal(np.mod(x, 1), 0))
```

I am going to copy this code into ks2 as well. Unless there are any objections.

**Comment by alejoe91** [comment]
Good catch! Should we have it in spikeextractors.extraction_tools instead?

**Comment by magland** [comment]
Yes. But let me run the SF pipeline first and make sure it resolves the
problem properly.

**Comment by alejoe91** [comment]
Ok sounds good

**Comment by magland** [comment]
I guess the last one to do is wave_clus

**Comment by alejoe91** [comment]
So did that fix the kilosort mismatches?

**Comment by magland** [comment]
Still running. Will know in a couple hours.

**Comment by magland** [comment]
Seemed to work. Not exactly the same results, but there were some very slight param differences. So I'd say we are good. Updated results are here: https://spikeforest.flatironinstitute.org

**Comment by samuelgarcia** [comment]
Can we close this ?

**Comment by magland** [comment]
Yes. Closing.
