### ISSUE TITLE
kilosort2 Out of memory on device, gpuDevice()

### ISSUE THREAD

**Issue by gmaggi** [SpikeInterface/spikesorters#172]
Hi,

A colleague of mine got the following error below when running kilosort2.

Apparently, other people also have it using kilosort2: https://github.com/cortex-lab/KiloSort/issues/176 . But it is also not clear to me where to run gpuDevice(), I guess somewhere in the kilosort2_master.m.

Is there a work around using spikeinterface?

Thanks,
Giuliano.

Found 0 splits, checked 1/244 clusters, nccg 0 
Found 33 splits, checked 101/277 clusters, nccg 30 
Found 34 splits, checked 101/278 clusters, nccg 30 
Found 35 splits, checked 101/279 clusters, nccg 30 
----------------------------------------Error using gpuArray/filter
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'

**Comment by gmaggi** [comment]
Hi,
Just to know if there are some tips to cope with the issue posted above.
Thanks,
Giuliano.

**Comment by gmaggi** [comment]
The dataset is ~250 GB. The GPU specs are:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   31C    P8    14W / 250W |      6MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by mhhennig** [comment]
I'm almost certain this GPU is insufficient, I have the same model and could sort only very small data sets. You could check by creating a small `SubRecordingExtractor` (just 5 min of data or so), and send this to Kilosort. This will probably still work, but for longer files it will fail. I have a GeForce RTX 2070, which appears to be a good compromise.

**Comment by gmaggi** [comment]
Thanks for the note.
If I understand correctly, kilosort2 divides the input in chunks of data. Thus, if the GPU is insufficient, that'd mean that  is insufficient  for a *single* chunk, and therefore I'd asume that the same error-result would pop up if Subrecording is used. 

Would it be correct?

**Comment by mhhennig** [comment]
I'm not really sure to be honest how it works internally. I just found that on a GTX 980 I could sort a 5 minute, 100 channel recording, but not a 15 min Neuropixels one.

**Comment by alejoe91** [comment]
Hi @gmaggi 

You can try to reduce the `NT` param (https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort2/kilosort2.py#L51), which is the one that controls the buffer size. This should reduce the amount of required GPU memory.

By default, this is `64 * 1024 + 64` (https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort2/kilosort2.py#L151 -  same as KS2 defaults). Maybe try out `32 * 1024 + 64`?

Cheers,
Alessio

**Comment by gmaggi** [comment]
Thanks @alejoe91 , ok, I'll try with `NT`. 
Is `ntbuff` also related? https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort2/kilosort2.py#L49

**Comment by alejoe91** [comment]
`ntbuff` should be the number of samples for the waveforms cutout, which is added to `NT` (better to double check with KS2 devs though). It shouldn't affect `NT` that much (64*1024 vs 64 samples), so I would leave it as is
