### ISSUE TITLE
Speed bottleneck with run_sorter file copying

### ISSUE THREAD

**Issue by timsainb** [SpikeInterface/spikesorters#188]
Hey all,

I'm running into a speed bottleneck when running run_sorter (e.g. run_kilosort2, run_ironsort2). The vast majority of the time it takes to run a sort is copying data into e.g. the tmp_KS2 folder. I'm wondering if you have any advice for how to improve the copy speeds (e.g. with parallelization at some point?). 

I'm basically loading a binary file, grabbing the relevant channels, doing some preprocessing, then sorting:

```python
recording = se.BinDatRecordingExtractor(
    dat_file,
    geom=geom_with_padding,
    sampling_frequency=recording_row.sample_rate,
    numchan=recording_row.num_channels_total,
    dtype=recording_dtype,
)
# subset neural channels
recording = se.SubRecordingExtractor(
    parent_recording=recording, channel_ids=recording_row.channels
)
recording.set_channel_groups(channel_group_groups, channel_group_channels)

# preprocess recording
recording_f = st.preprocessing.bandpass_filter(
    recording, freq_min=freq_min, freq_max=freq_max
)
recording_cmr = st.preprocessing.common_reference(recording_f)

# make a temporary directory to store neural data while spikesorting
tmpdir = tempfile.mkdtemp(dir=tmp_loc)

# perform kilosort sorting
sort = ss.run_kilosort2(
    recording,
    car=True,
    output_folder=Path(tmpdir) / "tmp_KS2",
    parallel=True,
    verbose=True,
    grouping_property=grouping_property,
    **sort_kwargs
)

```

The issue is that putting the data into tmp_KS2 for a 100GB recording takes hours. Is there some way to speed up the data writing speeds? E.g. parallelizing some step of the loop or changing chunk sizes for preprocessing? 

Thanks

**Comment by alejoe91** [comment]
Hi @timsainb 

You can indeed parallelize the process of writing to binary! I [recently](https://github.com/SpikeInterface/spikesorters/commit/e4bcf5801382d6d1dcd4f31e9cc1d6dcb33febfe) added two extra arguments to all sorters that write to binary: `n_jobs_bin` and `chunk_mb`.

You can try to use, for example, `n_jobs_bin=16` (or more, depending on your machine, and `chunk_mb=4000`. This will use chunks of 4Gb and split the writing job (note that in your case the writing job is more than just writing! The entire pipeline -- filtering - cmr - write will be processed in parallel) among 16 workers.

I expect this should speed thing up ~x10 times in your case. Let me know!

**Comment by timsainb** [comment]
Awesome, thanks!
