### ISSUE TITLE
base sorter should validate parameters

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikesorters#19]
@samuelgarcia 

I think the base sorter class needs some parameter validation so that it throws an exception if an unsupported parameter is passed in. For example, I mistakenly passed in curate=False rather than curation=False and there was no warning.

**Comment by alejoe91** [comment]
I agree. How do you deal with this in SF?

We could have something like:

```
if any([p for p in self.params.keys() not in self._default_params.keys()]):
    throw some error
```

What do you think?

**Comment by magland** [comment]
I think that code you wrote seems about right. Do you already check whether the required (non-optional) parameters are provided?

There's validation infrastructure built into mountaintools:
https://github.com/flatironinstitute/mountaintools/blob/master/mlprocessors/core.py

**Comment by alejoe91** [comment]
So the way we do it is merging the default_params with the user default params. So if a parameter is not given the default will be used.

I think we should discuss on Monday if we should integrate MT for this steps as well.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/22
