### ISSUE TITLE
Issue with kilosort 2.5

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spikesorters#190]
Hi,
I tried running the kilosort2.5 sorter on 2 different machines.
I tried using both running the sorter itself and the run_sorters method.
I get the same issue coming up:
"~/anaconda3/lib/python3.8/site-packages/spikesorters/kilosort2_5/kilosort2_5.py in _setup_recording(self, recording, output_folder)
    139         # save binary file
    140         input_file_path = output_folder / 'recording.dat'
--> 141         recording.write_to_binary_dat_format(input_file_path, dtype='int16', chunk_mb=p["chunk_mb"],
    142                                              n_jobs=p["n_jobs_bin"], verbose=self.verbose)
    143 

TypeError: write_to_binary_dat_format() got an unexpected keyword argument 'n_jobs'"

**Comment by alejoe91** [comment]
Hi, it seems you have an outdated version of spikeextractors. Can you try `pip install --upgrade spikeextractors`?

**Comment by benefron** [comment]
It returns that requirement already satisfied

**Comment by alejoe91** [comment]
Hi @benefron 

Can you paste the output of `pip list`? 

With `spikesorters==0.4.3` and `spikeextractors==0.9.3` things should work fine.

Kilosort2 calls the `recording.write_to_bin_dat_format()` ([here](https://github.com/SpikeInterface/spikesorters/blob/0.4.3/spikesorters/kilosort2/kilosort2.py#L130)) and those keyword arguments are indeed [present in the function](https://github.com/SpikeInterface/spikeextractors/blob/0.9.3/spikeextractors/recordingextractor.py#L705-L706)

So I suspect there is some mismatch in your installed versions.

**Comment by benefron** [comment]
spikecomparison                    0.3.1
spikeextractors                    0.9.3
spikefeatures                      0.1.1
spikeinterface                     0.11.0
spikemetrics                       0.2.2
spikesorters                       0.4.3
spiketoolkit                       0.7.2
spikewidgets                       0.5.1

**Comment by alejoe91** [comment]
That looks correct, but you can see from my links that the functions are compatible with those versions. Can you try to uninstall and re-install with pip?

**Comment by benefron** [comment]
I just did it before running the notebook.I can try again

**Comment by alejoe91** [comment]
Wait, what is the type of your RecordingExtractor? It might be extractor-specific!

**Comment by benefron** [comment]
open ephys binary

**Comment by alejoe91** [comment]
Then it should be fine..can you paste the entire error traceback?

**Comment by benefron** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-20-a9b019b30105> in <module>
----> 1 Kilo_test = ss.run_kilosort2_5(recording_cache,'/home/ben/Z/291220/2020-12-29_17-47-01_1429/A112_kilosort_test',parallel=False)

~/anaconda3/lib/python3.8/site-packages/spikesorters/sorterlist.py in run_kilosort2_5(*args, **kwargs)
    484         The spike sorted data
    485     """
--> 486     return run_sorter('kilosort2_5', *args, **kwargs)
    487 
    488 

~/anaconda3/lib/python3.8/site-packages/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     88                          verbose=verbose, delete_output_folder=delete_output_folder)
     89     sorter.set_params(**params)
---> 90     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
     91     sortingextractor = sorter.get_result()
     92 

~/anaconda3/lib/python3.8/site-packages/spikesorters/basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    128     def run(self, raise_error=True, parallel=False, n_jobs=-1, joblib_backend='loky'):
    129         for i, recording in enumerate(self.recording_list):
--> 130             self._setup_recording(recording, self.output_folders[i])
    131 
    132         # dump again params because some sorter do a folder reset (tdc)

~/anaconda3/lib/python3.8/site-packages/spikesorters/kilosort2_5/kilosort2_5.py in _setup_recording(self, recording, output_folder)
    139         # save binary file
    140         input_file_path = output_folder / 'recording.dat'
--> 141         recording.write_to_binary_dat_format(input_file_path, dtype='int16', chunk_mb=p["chunk_mb"],
    142                                              n_jobs=p["n_jobs_bin"], verbose=self.verbose)
    143 

TypeError: write_to_binary_dat_format() got an unexpected keyword argument 'n_jobs'

**Comment by alejoe91** [comment]
Ah! You have cached the recording!!! Ok then there was a bug there ([missing params](https://github.com/SpikeInterface/spikeextractors/blob/0.9.3/spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py#L84)) that is fixed on [master](https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py#L84-L85) :) 

Can you install `spikeextractors` form source? I'll make a new release with this fix in the next days

**Comment by benefron** [comment]
OK great,
Thanks I will install from source.

**Comment by benefron** [comment]
So now I get a new error:
Traceback (most recent call last):
  File "/home/labs/lampllab/befron/Dec_Jan2021/Sorting/kiloSort_test.py", line 132, in <module>
    recording_cache = se.CacheRecordingExtractor(recording_cmr)
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikeextractors-0.9.3-py3.7.egg/spikeextractors/cacheextractors.py", line 30, in __init__
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikeextractors-0.9.3-py3.7.egg/spikeextractors/recordingextractor.py", line 784, in write_to_binary_dat_format
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikeextractors-0.9.3-py3.7.egg/spikeextractors/extraction_tools.py", line 376, in write_to_binary_dat_format
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikeextractors-0.9.3-py3.7.egg/spikeextractors/extraction_tools.py", line 928, in _write_dat_one_chunk
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/labs/lampllab/befron/Dec_Jan2021/Sorting/kiloSort_test.py", line 144, in <module>
    Kilo_test = ss.run_kilosort2_5(recording_cache,'/home/labs/lampllab/befron/Dec_Jan2021/Sorting/A112_kilosort_test',parallel=False)
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikesorters-0.4.3-py3.7.egg/spikesorters/sorterlist.py", line 486, in run_kilosort2_5
    return run_sorter('kilosort2_5', *args, **kwargs)
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikesorters-0.4.3-py3.7.egg/spikesorters/sorterlist.py", line 90, in run_sorter
    sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikesorters-0.4.3-py3.7.egg/spikesorters/basesorter.py", line 130, in run
    self._setup_recording(recording, self.output_folders[i])
  File "/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikesorters-0.4.3-py3.7.egg/spikesorters/kilosort2_5/kilosort2_5.py", line 150, in _setup_recording
    with (source_dir / 'kilosort2_5_master.m').open('r') as f:
  File "/apps/RH7U2/gnu/anaconda/2020.02/python/3.7/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/apps/RH7U2/gnu/anaconda/2020.02/python/3.7/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/labs/lampllab/befron/.local/lib/python3.7/site-packages/spikesorters-0.4.3-py3.7.egg/spikesorters/kilosort2_5/kilosort2_5_master.m'

**Comment by alejoe91** [comment]
Right! Found the bug. Basically the .m files associated to kilosort2_5 were not copied to the site-packages.

Fixed here: https://github.com/SpikeInterface/spikesorters/pull/191

Can you install `spikesorters` from source?

**Comment by benefron** [comment]
Yes I will try.
Thanks

**Comment by benefron** [comment]
now I get this:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-23-04cd991c91a1> in <module>
----> 1 Kilo_test = ss.run_kilosort2_5(recording_cache,'/home/ben/Z/291220/2020-12-29_17-47-01_1429/A112_kilosort_test')

~/anaconda3/lib/python3.8/site-packages/spikesorters-0.4.3-py3.8.egg/spikesorters/sorterlist.py in run_kilosort2_5(*args, **kwargs)
    484         The spike sorted data
    485     """
--> 486     return run_sorter('kilosort2_5', *args, **kwargs)
    487 
    488 

~/anaconda3/lib/python3.8/site-packages/spikesorters-0.4.3-py3.8.egg/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     88                          verbose=verbose, delete_output_folder=delete_output_folder)
     89     sorter.set_params(**params)
---> 90     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
     91     sortingextractor = sorter.get_result()
     92 

~/anaconda3/lib/python3.8/site-packages/spikesorters-0.4.3-py3.8.egg/spikesorters/basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    128     def run(self, raise_error=True, parallel=False, n_jobs=-1, joblib_backend='loky'):
    129         for i, recording in enumerate(self.recording_list):
--> 130             self._setup_recording(recording, self.output_folders[i])
    131 
    132         # dump again params because some sorter do a folder reset (tdc)

~/anaconda3/lib/python3.8/site-packages/spikesorters-0.4.3-py3.8.egg/spikesorters/kilosort2_5/kilosort2_5.py in _setup_recording(self, recording, output_folder)
    144 
    145         # read the template txt files
--> 146         with (source_dir / 'kilosort2_5_master.m').open('r') as f:
    147             kilosort2_5_master_txt = f.read()
    148         with (source_dir / 'kilosort2_5_config.m').open('r') as f:

~/anaconda3/lib/python3.8/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
   1216         if self._closed:
   1217             self._raise_closed()
-> 1218         return io.open(self, mode, buffering, encoding, errors, newline,
   1219                        opener=self._opener)
   1220 

~/anaconda3/lib/python3.8/pathlib.py in _opener(self, name, flags, mode)
   1072     def _opener(self, name, flags, mode=0o666):
   1073         # A stub for the opener argument to built-in open()
-> 1074         return self._accessor.open(self, flags, mode)
   1075 
   1076     def _raw_open(self, flags, mode=0o777):

FileNotFoundError: [Errno 2] No such file or directory: '/home/ben/anaconda3/lib/python3.8/site-packages/spikesorters-0.4.3-py3.8.egg/spikesorters/kilosort2_5/kilosort2_5_master.m'

**Comment by alejoe91** [comment]
Looks like the same error as before..how did you reinstall `spikesorters`?

**Comment by benefron** [comment]
it seems similar but in a different location in the code
I did 
"pip uninstall spikesorters"
and then from the updated git repository did 
"python setup.py install"

**Comment by alejoe91** [comment]
I see! Sorry I'll take a closer look tomorrow

**Comment by benefron** [comment]
Sure,
Thanks for all the help
Ben

**Comment by alejoe91** [comment]
Hi @benefron 

Did you install from the master branch or the KS2_5_manifest branch? the changes were on the latter, but I just merged it to master. So if you repeat the installation as you did it should work now :)

**Comment by benefron** [comment]
Seems to be solved.
Thank you
