### ISSUE TITLE
wave_clus

### ISSUE THREAD

**Issue by shirquinn** [SpikeInterface/spikesorters#197]
Hi
I'm trying to run waveclus sorter via spikeinterface and it keeps getting stuck at this:
matlab -nosplash -wait -log -r run_waveclus

with the matlab command window blank

any idea why and how to solve this?
Thank you

**Comment by alejoe91** [comment]
Hi, 

What matlab version and what OS are you using?

Alessio

**Comment by shirquinn** [comment]
windows 10, 64-bit, 32GB RAM, Matlab R2020a

**Comment by shirquinn** [comment]
windows 10, 64-bit, 32GB RAM, Matlab R2020a
- I left it running and it produced an output after about 20 minutes for a 30 minutes recording- is this timing ok? should it be faster?
- what is the best curating approach for waveclus output? should i preform the curation via waveclus GUI since it allows to change the temperature in order to seperate clusters? i'd appreciate your recommendation

**Comment by alejoe91** [comment]
The timing sounds alright to me. It also depends on the number of channels. 

For manual curation you can use either the wave list GUI or export the output to Phy. Curation is very subjective in my opinion, so you can use whatever you prefer :)
