### ISSUE TITLE
running Kilosort 3 fails with matlab error `Index in position 1 exceeds array bounds (must not exceed 4)`

### ISSUE THREAD

**Issue by ChrisCurrin** [SpikeInterface/spikesorters#198]
running Kilosort 3 on '[Getting started with SpikeInterface](https://spikeinterface.readthedocs.io/en/latest/getting_started/plot_getting_started.html)' tutorial fails with matlab error `Index in position 1 exceeds array bounds (must not exceed 4)`

## Current Behavior
Running kilosort3 in place of mountainsort4 in the `plot_getting_started` fails.

Naturally, because a script is run, the error is rather generic: 
```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\Anaconda3\envs\mea-spike-pipe\lib\site-packages\spikesorters\basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    157                 for i, recording in enumerate(self.recording_list):
--> 158                     self._run(recording, self.output_folders[i])
    159             else:

~\Anaconda3\envs\mea-spike-pipe\lib\site-packages\spikesorters\kilosort3\kilosort3.py in _run(self, recording, output_folder)
    223         if retcode != 0:
--> 224             raise Exception('kilosort3 returned a non-zero exit code')
    225 

Exception: kilosort3 returned a non-zero exit code

During handling of the above exception, another exception occurred:

SpikeSortingError                         Traceback (most recent call last)
<ipython-input-19-6616bca91e6f> in <module>
----> 1 sorting_KS3 = ss.run_kilosort3(recording=recording_cmr, detect_threshold=6)

~\Anaconda3\envs\mea-spike-pipe\lib\site-packages\spikesorters\sorterlist.py in run_kilosort3(*args, **kwargs)
    524         The spike sorted data
    525     """
--> 526     return run_sorter('kilosort3', *args, **kwargs)
    527 
    528 

~\Anaconda3\envs\mea-spike-pipe\lib\site-packages\spikesorters\sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     91                          verbose=verbose, delete_output_folder=delete_output_folder)
     92     sorter.set_params(**params)
---> 93     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
     94     sortingextractor = sorter.get_result()
     95 

~\Anaconda3\envs\mea-spike-pipe\lib\site-packages\spikesorters\basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    167         except Exception as err:
    168             if raise_error:
--> 169                 raise SpikeSortingError(f"Spike sorting failed: {err}. You can inspect the runtime trace in "
    170                                         f"the {self.sorter_name}.log of the output folder.'")
    171             else:

SpikeSortingError: Spike sorting failed: kilosort3 returned a non-zero exit code. You can inspect the runtime trace in the kilosort3.log of the output folder.'
```

Fortunately, the `kilosort3_output` folder hangs around and I can run `kilosort3_master.m` in matlab with the `quit` commands removed.

When running `kilosort3_master.m`, it fails on this line:

```matlab
rez = datashift2(rez, 1); % last input is for shifting data
```

with error `Index in position 1 exceeds array bounds (must not exceed 4)`

## Context
- Windows 10 20h2 Build 19042.804
- Python 3.8.5
- SpikeInterface 0.11
- Spikesorters 0.4.3 (https://github.com/SpikeInterface/spikesorters/commit/8ea241cd98419d5e2c9b3ee7da26e770dee720b2)
- Matlab2020b
- RTX 3090 CUDA 10.2
- Kilosort3 (d8942c6 (HEAD -> main, origin/main, origin/HEAD) HEAD@{0}: clone: from https://github.com/MouseLand/Kilosort)

I have attached the kilosort3_output folder generated by `ss.run_kilosort3`

[kilosort3_output.zip](https://github.com/SpikeInterface/spikesorters/files/6001850/kilosort3_output.zip)

I can test this on an Ubuntu 20.04 distribution too if you'd like? Got the computer dual-booted.

**Comment by ChrisCurrin** [comment]
This fails on Ubuntu 20.04.2 LTS with CUDA Toolkit 11.2 (10.2 does not support Ubuntu 20.04) with the same message.

**Comment by alejoe91** [comment]
Hi Chris, 

The toy example is probably too small for KS3.

Can you try to use this instead:

`recording, sorting = se.example_datasets.toy_example(num_channels=64, duration=300)`

If this still fails, I would open an issue on the Kilosort repo.

Let me know
Alessio

**Comment by ChrisCurrin** [comment]
thanks, it makes it further into the process!

The subsequent error is:

```
Error using gpuArray/mean (line 37)
An unexpected error occurred trying to launch a kernel. The CUDA error was:
invalid configuration argumentERROR: MATLAB error Exit Status: 0x00000001
```

I'll investigate further and potentially open an issue on the Kilosort repo if I can't solve this.

Thanks for the larger data suggestions.
