### ISSUE TITLE
mountainsort4 curation should be False by default

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikesorters#20]
Turns out the curation for ms4 is VERY slow for larger channel counts. In theory it should be okay, but the present implementation is very slow. So I also think it should be False by default.

@alejoe91

**Comment by alejoe91** [comment]
Ok I'll change that. In SF you don't use curation then?

**Comment by magland** [comment]
No, not at the present time.

**Comment by magland** [comment]
(and we don't have metrics yet to penalize extra noise clusters)

**Comment by alejoe91** [comment]
Ok! My bad I thought curation was a necessary step most of the times.
I'll fix that. :)

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/21
