### ISSUE TITLE
Inconsistent interface for setting hdsort path

### ISSUE THREAD

**Issue by michaeljohnclancy** [SpikeInterface/spikesorters#200]
All other sorters currently allow for passing a Posix path to their path setting function (e.g. HDSortSorter.set_hdsort_path). HDSort's path setter does not allow for this, only allowing a string.

**Comment by alejoe91** [comment]
Thanks for spotting this, will fix it!

**Comment by alejoe91** [comment]
Actually no other sorters accepted `Path` types. I now added the possibility to use either `str` or `Path` fpr all sorters that require a path in this PR: https://github.com/SpikeInterface/spikesorters/pull/201
