### ISSUE TITLE
Installing sorters

### ISSUE THREAD

**Issue by crewl2** [SpikeInterface/spikesorters#205]
I'm having an issue installing klusta and spiking circus. I managed to install ironclust, but for some reason can't install the others. When trying to install using ss.KlustaSorter I'm getting an attribution error.

**Comment by alejoe91** [comment]
Hi, can you copy the entire error? 

Did you follow these guidelines to get the sorters installed? https://spikeinterface.readthedocs.io/en/latest/sortersinfo.html

**Comment by crewl2** [comment]
I did follow the installation guidelines. I may be writing the code wrong, but I'm trying to follow exactly what was given in spiketutorials. When trying to run Klusta it tells me I need to install it. When I look at installed sorters, klusta doesn't come up. 

Here's my error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-39-f736376767d3> in <module>
----> 1 ss.KlustaSorter.set.klusta_path('./klusta')
      2 ss.installed_sorters()

AttributeError: type object 'KlustaSorter' has no attribute 'set'

**Comment by alejoe91** [comment]
Hi, klusta doesn't need a path to be set because it's a python package (there's no mention to setting a path in the instructions!)

**Comment by crewl2** [comment]
I thought so! But when I use ss.intstalled_sorters() it doesn't show that klusta has been installed. I followed all the installation instructions and when I try to run the sorter I get the installation error. 

code:

# run spike sorting by group 
sorting_KL = ss.run_klusta(recording_cache, adjacency_radius=50, 
                                      output_folder='results_split_klusta', 
                                      grouping_property='group', parallel=True)
print(f'Klusta found {len(sorting_KL.get_unit_ids())} units')

Error:

AssertionError                            Traceback (most recent call last)
<ipython-input-15-0eddad1abfdb> in <module>
      2 sorting_KL = ss.run_klusta(recording_cache, adjacency_radius=50, 
      3                                       output_folder='results_split_klusta',
----> 4                                       grouping_property='group', parallel=True)
      5 print(f'Klusta found {len(sorting_KL.get_unit_ids())} units')

~/opt/anaconda3/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_klusta(*args, **kwargs)
    263         The spike sorted data
    264     """
--> 265     return run_sorter('klusta', *args, **kwargs)
    266 
    267 

~/opt/anaconda3/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     86 
     87     sorter = SorterClass(recording=recording, output_folder=output_folder, grouping_property=grouping_property,
---> 88                          verbose=verbose, delete_output_folder=delete_output_folder)
     89     sorter.set_params(**params)
     90     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)

~/opt/anaconda3/lib/python3.7/site-packages/spikesorters/klusta/klusta.py in __init__(self, **kargs)
     68 
     69     def __init__(self, **kargs):
---> 70         BaseSorter.__init__(self, **kargs)
     71 
     72     @classmethod

~/opt/anaconda3/lib/python3.7/site-packages/spikesorters/basesorter.py in __init__(self, recording, output_folder, verbose, grouping_property, delete_output_folder)
     49 
     50         assert self.is_installed(), """The sorter {} is not installed.
---> 51         Please install it with:  \n{} """.format(self.sorter_name, self.installation_mesg)
     52         if self.requires_locations:
     53             if 'location' not in recording.get_shared_channel_property_names():

AssertionError: The sorter klusta is not installed.
        Please install it with:  

To use Klusta run:

       >>> pip install Cython h5py tqdm
       >>> pip install click klusta klustakwik2

    More information on klusta at:
      * https://github.com/kwikteam/phy"
      * https://github.com/kwikteam/klusta

**Comment by alejoe91** [comment]
Hi, then it didn't install properly. Try to reinstall it! If klusta doesn't show up in the list of installed sorters, then it won't run

**Comment by AlanoudAlsubhi** [comment]
Hi, 
I am having the same issue. I did install Klusta by following the given instruction but when I run ss.intstalled_sorters(), it returns an empty array. What might be the issue here? 

Thank you, 
Alanoud

**Comment by alejoe91** [comment]
What is the output of the terminal when you try to install klusta?

**Comment by AlanoudAlsubhi** [comment]
Microsoft Windows [Version 10.0.18363.1256]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\aalsubhi>pip install klusta
Requirement already satisfied: klusta in c:\users\aalsubhi\appdata\local\programs\python\python39\lib\site-packages (3.0.16)

**Comment by alejoe91** [comment]
Did you install klustakwik2 as well?

**Comment by crewl2** [comment]
I'm getting the same thing. Requirement already satisfied. I can even activate klusta in the terminal.

**Comment by alejoe91** [comment]
Klustakwik2?

**Comment by AlanoudAlsubhi** [comment]
Microsoft Windows [Version 10.0.18363.1256]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\aalsubhi\Downloads\klusta-master>pip install klustakwik2
Collecting klustakwik2
  Using cached klustakwik2-0.2.6-cp39-cp39-win_amd64.whl
Installing collected packages: klustakwik2
Successfully installed klustakwik2-0.2.6

**Comment by crewl2** [comment]
pip install klustakwik2
Requirement already satisfied: klustakwik2 in /Users/laurencrew/opt/miniconda3/lib/python3.8/site-packages (0.2.6)

**Comment by AlanoudAlsubhi** [comment]
![image](https://user-images.githubusercontent.com/79871345/110528474-2f570e80-80e6-11eb-920c-cf6879f30bff.png)

**Comment by alejoe91** [comment]
Are you sure you are using the right environment? It doesn't look installed here!

**Comment by AlanoudAlsubhi** [comment]
Can you briefly explain what you mean by the "right environment"? So even if klusta is activated on the terminal it is not necessary installed on python?  

I tried to follow the installation instructions on [here](https://github.com/kwikteam/klusta/#quick-install-guide) but I might have missed something out.

**Comment by alejoe91** [comment]
Sure! So I believe that when you run the `jupyter notebook` command, the notebook starts in the wron environment, meaning a different python. In order to check this, you can run `pip list` from you command line (after activating the klusta env), and also run `!pip list` in the jupyter notebook. They'll probably be different! This is because the python version will be different (you can try to run `which python` from the terminal and `!which python` from the notebook). I hope this clarifies it a bit!

To make sure that the notebook runs on the same python, you need to install jupyter via conda: `conda install jupyter`

**Comment by alejoe91** [comment]
If you still get environment mismatches, you can try to install `nb_conda_kernels`:

`conda install nb_conda_kernels`

**Comment by AlanoudAlsubhi** [comment]
@alejoe91 This actually clarified A LOT. It helped me to figure out how environments work and organize accordingly. 
Now when I run ss.intstalled_sorters() Klusta shows up. 

Thanks a lot.
