### ISSUE TITLE
Passing 'run_sorter_kwargs' with 'raise_error' throws Bad Parameter

### ISSUE THREAD

**Issue by eejd** [SpikeInterface/spikesorters#206]
When attempting to log rather than throw errors during grouped clustering, you need to pass `raise_error` to `BaseSorter._run()` but the (documented) way to do that from `run_sorter` is to pass `run_sorter_kwargs` dictionary with `raise_error` as a parameter. When you do this, you get:

```
File "repos/spikesorters/spikesorters/sorterlist.py", line 92, in run_sorter
    sorter.set_params(**params)
  File "repos/spikesorters/spikesorters/basesorter.py", line 114, in set_params
    raise AttributeError('Bad parameters: ' + str(bad_params))
AttributeError: Bad parameters: ['run_sorter_kwargs']
```

**Comment by alejoe91** [comment]
Hi! The `run_sorter_kwargs` is for the `run_sorters` function, not the `run_sorter`. For the latter, you can pass the arguments directly. Or are you using the `run_sorters` function?

**Comment by eejd** [comment]
Ah, correct, I was using `run_sorter` currently. However, a second problem occurred when I used `raise_error` directly: the output collection doesn't have `raise_error` protection so `run_sorter` still causes an Exception to halt the process. In this case, the goals is to allow groups individually to fail without stopping the whole process. (e.g. a tetrode is flagged with multiple bad channels and KS will fail, but the next tetrode could be processed.) A related question is are the `run_sorter` and `run_sorters` the right approach for this goal?

**Comment by alejoe91** [comment]
Right! That should be fixed :) I'll make a PR soon!
