### ISSUE TITLE
IronClustSorter writes and uses MDA rather than .DAT file, so writing data can't be parallelized 

### ISSUE THREAD

**Issue by timsainb** [SpikeInterface/spikesorters#216]
Spikeinterface's interface with ironclust chose .mda. 
The problem with .mda, is that write_recording with MDA isn't parallelized (see https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extraction_tools.py#L375). So writing to MDA is much slower. 

It seems like there are two ways to fix this:
1) Use a different file format. Ironclust is can take in several formats - .mda, .dat, .bin. 
2) find a way to parallelize writing an MDA, since it seems like it's just a .bin with a header? 

### If you were to do 1, you would want to give the option to switch out the MdaRecordingExtractor (https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/ironclust/ironclust.py#L161):
```python
 se.MdaRecordingExtractor.write_recording(recording=recording, save_path=str(dataset_dir),
                                                 n_jobs=p["n_jobs_bin"], chunk_mb=p["chunk_mb"], verbose=self.verbose)
```

with `BinDatRecordingExtractor`

Then when running ironclust, point it toward raw.dat rather than raw.mda (https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/ironclust/ironclust.py#L199)

### If you were to do 2, it seems like the solution wouldfinding a way to parallelize MDA writing here: https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/mdaextractors/mdaextractors.py#L152

```python
with save_file_path.open('wb') as f:
            header = MdaHeader(dt0=dtype, dims0=(num_chan, num_frames))
            header.write(f)
            # takes care of the chunking
            write_to_binary_dat_format(recording, file_handle=f, dtype=dtype, n_jobs=n_jobs, chunk_size=chunk_size, chunk_mb=chunk_mb, verbose=verbose)
```

Since write_to_binary_dat_format doesn't let you parallelize binary writing with file handles (only save_paths, which are written with np.memmap), would be possible to instead write MDA as an mmap, and then change the header after? 

It seems to me like 1 is probably the better option, although if you can parallelize writing MDAs that would extend to other sorters which use MDAs.

**Comment by samuelgarcia** [comment]
I vote for binary format.

**Comment by alejoe91** [comment]
Ahhh I see! Sorry I misinterpreted it! I think option 1 would be better, but ironclust is not maintained anymore as far as I know. Probably easier to add parallelization to the mda write function.

**Comment by timsainb** [comment]
That makes sense, thanks. The only reason I'm using ironclust here is its the only sorter that I can find that sorts multiday recordings of 16-64ch  neuronexus probes (any suggestions appreciated). 

The _write_dat_one_chunk function, that allows parallelization with .dat files creates a np.memmap, writes to it in parallel. 

.mda files just `file_handle.write(traces.tobytes())` sequentially. 

This is probably a naive question, but is there a way to create the memmap then switch out the header to the MDA header?

**Comment by alejoe91** [comment]
@timsainb yeah I can imagine you need parallelization for those many channels. Have you tried Kilosort2-3 or herding spikes? Those also can handle large channel counts.

I think creating a memmap and writing then the header is doable. The memmap has no header IMO, so we should only figure out how to append at the beginning of the file.

**Comment by samuelgarcia** [comment]
@timsainb : tell me you have try tridesclous :)
