### ISSUE TITLE
command not found error for klusta and spykingcircus (sorters are installed)

### ISSUE THREAD

**Issue by atranvan** [SpikeInterface/spikesorters#217]
Hi, 

I just performed an install of spikeinterface and several sorters through instructions found [here](https://spikeinterface.readthedocs.io/). This is running on a cluster. spikeinterface and python-based sorters were installed in the same freshly created conda environment with python 3.7

my problem seems similar to issue #88  

I try to run the getting [tutorial](https://spikeinterface.readthedocs.io/en/latest/getting_started/plot_getting_started.html) in a notebook. 

My installed sorters are correctly displayed :  
`Installed sorters ['kilosort2', 'klusta', 'mountainsort4', 'spykingcircus']`

However only mountainsort4 seems to be running

running:
`sorting_KL = ss.run_klusta(recording_cmr, verbose = True)`
returns:
```
Writing to binary .dat file: 100%|##########| 1/1 [00:00<00:00,  6.45it/s]

RUNNING SHELL SCRIPT: /camp/lab/rancze/working/tranvaa/spikeinterface/klusta_output/run_klusta.sh
/camp/lab/rancze/working/tranvaa/spikeinterface/klusta_output/run_klusta.sh: line 2: klusta: command not found

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/.conda/envs/spikeinterface3/lib/python3.7/site-packages/spikesorters/basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    157                 for i, recording in enumerate(self.recording_list):
--> 158                     self._run(recording, self.output_folders[i])
    159             else:

~/.conda/envs/spikeinterface3/lib/python3.7/site-packages/spikesorters/klusta/klusta.py in _run(self, recording, output_folder)
    151         if retcode != 0:
--> 152             raise Exception('klusta returned a non-zero exit code')
    153 

Exception: klusta returned a non-zero exit code

During handling of the above exception, another exception occurred:

SpikeSortingError                         Traceback (most recent call last)
<ipython-input-13-ab9a9964dd13> in <module>
----> 1 sorting_KL = ss.run_klusta(recording_cmr, verbose = True)

~/.conda/envs/spikeinterface3/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_klusta(*args, **kwargs)
    266         The spike sorted data
    267     """
--> 268     return run_sorter('klusta', *args, **kwargs)
    269 
    270 

~/.conda/envs/spikeinterface3/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     91                          verbose=verbose, delete_output_folder=delete_output_folder)
     92     sorter.set_params(**params)
---> 93     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
     94     sortingextractor = sorter.get_result(raise_error=raise_error)
     95 

~/.conda/envs/spikeinterface3/lib/python3.7/site-packages/spikesorters/basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    167         except Exception as err:
    168             if raise_error:
--> 169                 raise SpikeSortingError(f"Spike sorting failed: {err}. You can inspect the runtime trace in "
    170                                         f"the {self.sorter_name}.log of the output folder.'")
    171             else:

SpikeSortingError: Spike sorting failed: klusta returned a non-zero exit code. You can inspect the runtime trace in the klusta.log of the output folder.
```

the klusta.log file just countain the line above though "/camp/lab/rancze/working/tranvaa/spikeinterface/klusta_output/run_klusta.sh: line 2: klusta: command not found"

similar error with spyking circus and kilosort2 (for kilosort2, matlab does start)
kilosort2 : I have linked my regular folder through:

```
kilosort2_path = os.path.join(path, './Kilosort2')
ss.Kilosort2Sorter.set_kilosort2_path(kilosort2_path)
```

 ###  trying to run the sorters independently :
 
- Klusta is properly installed and can be run separately though. I have run klusta from this conda environment using my regular scripts, and it runs fine. 
- Kilosort2 is also properly installed - however I can't rule out that running it through a notebook on the cluster is not an issue (I usually run it on a different type of node)

- I can also run spyking-circus installed in that environment from terminal 

Do you have any idea where to start troubleshooting this so that spikeinterface can find the sorters?

thanks in advance !

**Comment by farazmoradi** [comment]
The same Issue!

**Comment by alejoe91** [comment]
Hi, 

CLI-based sorters (as klusta and spyking-circus) and matlab-based (e.g. Kilosort) are run through subprocesses. It seems that the subprocess doesn't start in the correct environment. 

Can I ask more information on what kind of cluster you are using?

**Comment by atranvan** [comment]
Hi Alessio,

I am using a HPC cluster. I am slightly perplexed as to why moutainsort runs and not the other sorters though?

**Comment by alejoe91** [comment]
Hi @atranvan 

So mountainsort4 (and other sorters - tridesclous, herdingspikes) use directly the SpikeInterface API to run the sorting, so basically they are run in the same environment. The other sorters launch subprocesses either from the command line interface (klusta, spyking circus) or from matlab (kilosort, ironclust, waveclus).

I suspect that spawning a new sub-process in the HPC does not use 1) the same python environment and 2) doesn't have access to the ENV variables.

A possible workaround could be to activate your environment (e.g. `conda activate spikeinterface`) and add paths to the sorters (e.g. `KILOSORT2_PATH="/.../Kilosort"`) directly in your `.bashrc`. The problem of note finding matlab could probably be solved similarly by adding a `module load matlab` to the same file. 

Let me know if this solves the issue!

**Comment by atranvan** [comment]
Hi Alessio,

I found a solution in the spirit of what you suggest. I usually run jupyter outside any specific conda environment and use ipykernel to load kernels corresponding to the desired environments, and that works as far as importing packages go.
When I instead activate the environment and run jupyter lab from there, the subprocesses to run the other sorters now launch properly. 
Thanks a lot for your help!
