### ISSUE TITLE
don't modify recording extractors inside functions when not expected

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikesorters#29]
For example, the following is not good (in kilosort2.py):

```
if 'location' not in recording.get_channel_property_names():
            print("'location' information is not found. Using linear configuration")
            for i_ch, ch in enumerate(recording.get_channel_ids()):
                recording.set_channel_property(ch, 'location', [0, i_ch])
```

**Comment by alejoe91** [comment]
I do the same in MS4 otherwise it fails if it doesn't have geometry information..
I see your point though. Is there a workaround?

**Comment by magland** [comment]
yes, you'll see in my PR for kilosort2 wrapper

**Comment by alejoe91** [comment]
for mountainsort it's tricky because the location info is accessed inside ml_ms4alg...

**Comment by magland** [comment]
that is tricky. i will ponder about it.

**Comment by alejoe91** [comment]
now the extractor is only modified at the base extractor level. I think this is the correct approach. There is no harm in adding dummy locations so that sorters can run.
