### ISSUE TITLE
missing requests dependency due to madio (ironclust)

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikesorters#35]
This make spiketoolkit PR bugy on travis.

**Comment by samuelgarcia** [comment]
If IronClust is working, why not moving mdaio and mdaextractor in spikeextractor.
No ?

Or do we force requests module in spiketoolkit installation for this particular IO ?

**Comment by alejoe91** [comment]
I think that was a WIP.

Both mdaio and MdaRecordingExtractor2 should be moved to spikeextactors @magland

**Comment by magland** [comment]
Working on this now.

**Comment by magland** [comment]
A bit more difficult than I suspected. Our mda recording extractors have diverged to some extent. Can we leave things the way they are for now (for fear of breaking something) and I promise I will do a good cleanup. For now I will put some comments in the ironclust code to this effect.

@samuelgarcia, @alejoe91, @colehurwitz, is this okay for now?

**Comment by samuelgarcia** [comment]
The important is to promise :)
Ok for me, no worry.

**Comment by alejoe91** [comment]
I moved this to a utils folder

**Comment by alejoe91** [comment]
Now moved everything to SE and added chunk mechanism to the standard MdaRecordingExtractor. 
The only mdaio needed and kept are the matlab ones
