### ISSUE TITLE
MS4 does not recieve sampling rate from recording extractor

### ISSUE THREAD

**Issue by nahawtho** [SpikeInterface/spikesorters#47]
It does not seem like MS4 inherits sampling frequency in the same way Klusta does: 
`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-73-d7750f034091> in <module>
----> 1 sw.plot_rasters(sorting_MS4)

~/.local/lib/python3.6/site-packages/spikewidgets/widgets/rasterswidget/rasterswidget.py in plot_rasters(sorting, sampling_frequency, unit_ids, color, figure, ax)
     30     if sampling_frequency is None:
     31         if sorting.get_sampling_frequency() is None:
---> 32             raise Exception("Sampling rate information is not in the SortingExtractor. "
     33                             "Provide the 'sampling_frequency' argument")
     34         else:

Exception: Sampling rate information is not in the SortingExtractor. Provide the 'sampling_frequency' argument`

(Everything is installed from master branches)

If I perform sorting on a recording w a sampling rate w Klusta on the other hand, spike rasters would not is not missing sampling rate.

**Comment by alejoe91** [comment]
Hi,

Did you run MS4 with `sorters.run_mountainsort4` ?
In that case it sould inherit the sampling_frequqncy (https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/basesorter.py#L167).
If it doesn't, then it's a bug :)

Unfortunately, MS4 format does not carry fs info. For the other sorters this can be loaded from the sorter extractror directly.

If you are using the class `Mountainsort4Sorter` then you can use the `set_sampling_frequency()` function of the sorting extractor.

**Comment by mhhennig** [comment]
I actually observed that too, will see if I can find out what happens...

**Comment by alejoe91** [comment]
@mhhennig if you use the class approach, then you need to manually `sorting.set_sampling_frequency` for MS4, because the MDA format does not have that info. If you use the launcher, this is done automatically for all sorters: the sampling_frequency is copied from the recording extractor.

**Comment by samuelgarcia** [comment]
Maybe our wrapper could write a txt/json fil into the MS4 folder to make it automatically.
No ?

**Comment by alejoe91** [comment]
we discussed about it with @magland and he wouldn't want to change the format. I don't think this is a big issue. Most of the times one would use `run_mountainsort4` and in that case the sampling frequency is loaded

**Comment by alejoe91** [comment]
This is fixed now
