### ISSUE TITLE
Path problem for Windows

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikesorters#57]
There are lots of path strings among different sorters, e.g. cmd strings in *klusta* and *spyking_circus*, and the path string are all in **UNIX** style and thus would break on Windows.

**Comment by alejoe91** [comment]
where are the path strings in klusta and SC? I think we use pathlib in all sorters to avoid this

**Comment by Shawn-Guo-CN** [comment]
> where are the path strings in klusta and SC? I think we use pathlib in all sorters to avoid this

My bad, you're right. The file path style is correct. The bug is caused by other things.
