### ISSUE TITLE
Mountainsort4 timeout on tests

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikesorters#62]
Mountainsort4 seems to be having some performance issues so much so that it times out on our travis tests. Maybe this can be fixed? @magland @alejoe91

**Comment by alejoe91** [comment]
You mean that it's slow?

**Comment by colehurwitz** [comment]
Yeah, it always times out since it is slow.

**Comment by alejoe91** [comment]
It's strange because it only times out sometimes..

**Comment by samuelgarcia** [comment]
On which dataset ?

**Comment by magland** [comment]
Strange. Could you tell exactly which dataset it is having trouble with?
J

**Comment by colehurwitz** [comment]
It usually times out on the third test:

**Comment by samuelgarcia** [comment]
Hi I experience the same problem with MS4.

On my mahcine I am not able to build gallery example for instance **plot_1_compare_two_sorters.py** is blocking for always.

**Comment by samuelgarcia** [comment]
Note clone from matser of ml_ms4alg do not solve the problem.

**Comment by samuelgarcia** [comment]
@magland : could you try to run
```
python spikeinterface/examples/modules/comparison/plot_1_compare_two_sorters.py
```
and tell me if it works for you.

I think this prevent the release because doc can't build.
No ?

**Comment by mafrasiabi** [comment]
even with a toy dataset it doesn't work for me and will stuck in a pool , even though I have put num_workers = 1

**Comment by alejoe91** [comment]
This was due to the threading system. Should be fixed now
