### ISSUE TITLE
Tridesclous doesn't work when several channel groups are present and spike sorting is not done by group.

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikesorters#73]
@samuelgarcia 

running 
`sorting_tdc = sorters.run_tridesclous(recording)` gives this error when the recording has different channel groups:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-56-9ed34ecc1595> in <module>
      1 # run spike sorting on entire recording
----> 2 sorting_tdc = sorters.run_tridesclous(recording_prb)

~/Documents/Codes/spike_sorting/spikeinterface/spikesorters/spikesorters/sorterlist.py in run_tridesclous(*args, **kargs)
    104 
    105 def run_tridesclous(*args, **kargs):
--> 106     return run_sorter('tridesclous', *args, **kargs)
    107 
    108 

~/Documents/Codes/spike_sorting/spikeinterface/spikesorters/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, **params)
     52     sorter.set_params(**params)
     53     sorter.run()
---> 54     sortingextractor = sorter.get_result()
     55 
     56     return sortingextractor

~/Documents/Codes/spike_sorting/spikeinterface/spikesorters/spikesorters/basesorter.py in get_result(self)
    146 
    147     def get_result(self):
--> 148         sorting_list = self.get_result_list()
    149         if len(sorting_list) == 1:
    150             sorting = sorting_list[0]

~/Documents/Codes/spike_sorting/spikeinterface/spikesorters/spikesorters/basesorter.py in get_result_list(self)
    141         sorting_list = []
    142         for i, _ in enumerate(self.recording_list):
--> 143             sorting = self.get_result_from_folder(self.output_folders[i])
    144             sorting_list.append(sorting)
    145         return sorting_list

~/Documents/Codes/spike_sorting/spikeinterface/spikesorters/spikesorters/tridesclous/tridesclous.py in get_result_from_folder(output_folder)
    179     @staticmethod
    180     def get_result_from_folder(output_folder):
--> 181         sorting = se.TridesclousSortingExtractor(folder_path=output_folder)
    182         return sorting
    183 

~/Documents/Codes/spike_sorting/spikeinterface/spikeextractors/spikeextractors/extractors/tridescloussortingextractor/tridescloussortingextractor.py in __init__(self, folder_path, chan_grp)
     25             # if chan_grp is not provided, take the first one if unique
     26             chan_grps = list(self.dataio.channel_groups.keys())
---> 27             assert len(chan_grps) == 1, 'There are several in the folder chan_grp, specify it'
     28             chan_grp = chan_grps[0]
     29 

AssertionError: There are several in the folder chan_grp, specify it
```

TDC version: 1.2.2

Any idea why this happens? is it a TDC or a spikesorters problem? Seems to be coming from `dataio`

**Comment by alejoe91** [comment]
Same error on ubuntu, macOS, and Windows

**Comment by samuelgarcia** [comment]
I will try to have a look.
But normally the multi group is handle inside BaseSorter by splitting the recording into sevral pieces.
And there a unitest for that.
Is it a differents scenario than the test ? If yes could you write the test ?

Are you using tridesclous for real ?

**Comment by samuelgarcia** [comment]
OK I anderstand.
It is in fact running the bug arrive when retrieving the data. No ?

**Comment by alejoe91** [comment]
Yes I think so! I'm presenting SI at a workshop and we ran into the issue. TDC runs fine but it's the data retrieval that fails

**Comment by samuelgarcia** [comment]
OK I anderstand the situation.
For this I need to make a very little patch in tridesclous but infortunatly tridesclous is in the middle of a big big refactoring. So I can't make a release now.

What I propose is to make a uggly patch in spikextractor.tridesclous to fix this. It will more simple.
I then after a release of TDC remove that patch.

Is it OK ?

**Comment by alejoe91** [comment]
ok sounds good to me

**Comment by samuelgarcia** [comment]
@alejoe91 : I don't anderstand something.
In our test **SorterCommonTestSuite.test_several_groups** that tdc already pass.
We have a **sorting = sorter.get_result()** so we should have the bug here too.
No ?
What is the difrrence with your case ?

**Comment by samuelgarcia** [comment]
Dear Alessio,

It is a more general problem.
See https://github.com/SpikeInterface/spikeextractors/issues/296

In conclusion:
You should not stigmatize TDC for this bug but you should publically declared your gratitude to TDC because thanks to well internal protection, TDC made possible to discover a deep deep bug for a very very rare case.
:)
héhé.

Cheers.
