### ISSUE TITLE
Spike detection only?

### ISSUE THREAD

**Issue by McD-NMI** [SpikeInterface/spikesorters#75]
I was wondering if there is any possibility to run spike detection only with SpikeInterface, without doing any sorting. For example, if I only care about the whole network activity and not any individual unit.

**Comment by alejoe91** [comment]
Hi @McD-NMI 

We can implement something like: `ss.detect_spikes(recording)` that just extracts and aligns the peaks channel-wise. Is that what you were thinking about?

**Comment by McDr** [comment]
Yes, exactly what I was thinking!

**Comment by alejoe91** [comment]
I can implement a very simple detector (> n_snr * MAD) and maybe we can add some more sophisticated method later. Will make a PR soon :)

**Comment by alejoe91** [comment]
@McD-NMI @McDr you can test this https://github.com/SpikeInterface/spikesorters/pull/77

We are still debating on whether this should be in spiksorters or spiketoolkit, but it should work :)

**Comment by magland** [comment]
@alejoe91 I thought about this further and would propose to make a namespace of spiketoolkit called sorting (going along with preprocessing, etc). It is reserved for general methods related to parts of spike sorting. The spikesorters repo would be reserved for complete spike sorting algorithms.

**Comment by samuelgarcia** [comment]
Yes. Agree with jeremy.

Le mar. 3 déc. 2019 15:34, Jeremy Magland <notifications@github.com> a
écrit :

**Comment by colehurwitz** [comment]
I agree as well (sorry for the slow reply)

**Comment by alejoe91** [comment]
:+1:  I'll move it!

**Comment by samuelgarcia** [comment]
Alessio, normally you convince every one in each debate but not this time.
You must be tired
 :)

**Comment by alejoe91** [comment]
Ahahaha I agree with the group :)

**Comment by alejoe91** [comment]
moved here: https://github.com/SpikeInterface/spiketoolkit/pull/292
