### ISSUE TITLE
error running sorting tutorial with Klusta and Spyking Circus

### ISSUE THREAD

**Issue by atranvan** [SpikeInterface/spikesorters#78]
Hi,

I have just installed spikeinterface (pip install) on Ubuntu 16.04 in an Anaconda environment. I have also installed several sorters via pip and am running into an error when trying [this tutorial](https://spikeinterface.readthedocs.io/en/latest/modules/sorters/plot_1_sorters_example.html).

The sorters are correctly installed:
```
print(ss.installed_sorter_list)
```

Output:
```
[<class 'spikesorters.klusta.klusta.KlustaSorter'>, <class 'spikesorters.mountainsort4.mountainsort4.Mountainsort4Sorter'>, <class 'spikesorters.spyking_circus.spyking_circus.SpykingcircusSorter'>, <class 'spikesorters.herdingspikes.herdingspikes.HerdingspikesSorter'>]
```

From those, only herdingspikes and moutainsort are giving me an output.
Running the Klusta sorter gives this error:
```
recording, sorting_true = se.example_datasets.toy_example(duration=10, seed=0)
sorting_KL = ss.run_klusta(recording, output_folder='/media/tranvaa/Data2/TDT/tmp_KL')
print(sorting_KL.get_unit_ids())
```

Output:
```
RUNNING SHELL SCRIPT: /tmp/tmp_shellscript56jozohp/script.sh

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-10-ee3cd57ec55c> in <module>
      1 # Klusta spike sorting
----> 2 sorting_KL = ss.run_klusta(recording, output_folder='/media/tranvaa/Data2/TDT/tmp_KL')
      3 print(sorting_KL.get_unit_ids())

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/sorterlist.py in run_klusta(*args, **kargs)
    100 
    101 def run_klusta(*args, **kargs):
--> 102     return run_sorter('klusta', *args, **kargs)
    103 
    104 

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, **params)
     51                          parallel=parallel, verbose=verbose, delete_output_folder=delete_output_folder)
     52     sorter.set_params(**params)
---> 53     sorter.run()
     54     sortingextractor = sorter.get_result()
     55 

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/basesorter.py in run(self)
    100         if not self.parallel:
    101             for i, recording in enumerate(self.recording_list):
--> 102                 self._run(recording, self.output_folders[i])
    103         else:
    104             # run in threads

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/klusta/klusta.py in _run(self, recording, output_folder)
    147 
    148         if retcode != 0:
--> 149             raise Exception('klusta returned a non-zero exit code')
    150 
    151         if not (output_folder / 'recording.kwik').is_file():

Exception: klusta returned a non-zero exit code
```

I get a similar error with spyking circus:
```
sorting_SC = ss.run_spykingcircus(recording, output_folder='tmp_SC')
print('Units found with Spyking Circus:', sorting_SC.get_unit_ids())
```

Output:
```
RUNNING SHELL SCRIPT: /tmp/tmp_shellscriptnu853fvw/script.sh

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-9-0dc492ebdd2f> in <module>
      1 # SpyKING Circus spike sorting
----> 2 sorting_SC = ss.run_spykingcircus(recording, output_folder='tmp_SC')
      3 print('Units found with Spyking Circus:', sorting_SC.get_unit_ids())

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/sorterlist.py in run_spykingcircus(*args, **kargs)
    124 
    125 def run_spykingcircus(*args, **kargs):
--> 126     return run_sorter('spykingcircus', *args, **kargs)
    127 
    128 

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, **params)
     51                          parallel=parallel, verbose=verbose, delete_output_folder=delete_output_folder)
     52     sorter.set_params(**params)
---> 53     sorter.run()
     54     sortingextractor = sorter.get_result()
     55 

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/basesorter.py in run(self)
    100         if not self.parallel:
    101             for i, recording in enumerate(self.recording_list):
--> 102                 self._run(recording, self.output_folders[i])
    103         else:
    104             # run in threads

~/anaconda3/envs/spikeinterfaceenv/lib/python3.6/site-packages/spikesorters/spyking_circus/spyking_circus.py in _run(self, recording, output_folder)
    137 
    138         if retcode != 0:
--> 139             raise Exception('spykingcircus returned a non-zero exit code')
    140 
    141     @staticmethod

Exception: spykingcircus returned a non-zero exit code
```

Any idea what's wrong?
thanks a lot in advance!

**Comment by alejoe91** [comment]
Hi @atranvan 

Are you running it from jupyter? Can you check the terminal output when running the sorters? You should get a lot of messages on what the spike sorting is doing. That should be quite informative on what the problem is :)

**Comment by atranvan** [comment]
Hi Alessio,

thanks for the quick reply. Indeed this is from Jupyter. Weirdly I do not get the same behaviour in a Python console.

From Jupyter, the terminal output is:
 
```
/tmp/tmp_shellscripteygot6u5/script.sh: line 2: klusta: command not found
 
```

or 
 
```
  /tmp/tmp_shellscriptouei02g2/script.sh: line 2: spyking-circus: command not found

```



Strangely, from a Python console, in the same conda environment, Klusta runs fine.
With Spyking circus, I had an error that I could solve by installing PyQt5.

Do you have any idea why the code does not work from the notebook? I realize this is not necessarily a spikeinterface question, but if any other users have run into this I'd be interested. I have never had such an issue myself with jupyter while running subprocesses from there.

Thanks !

Alex

**Comment by atranvan** [comment]
Hey,

actually I realized this is because the path from the notebook was wrong (I was using my base jupyter instead of the environment jupyter)... It all works now, Thanks for the pointers!

Cheers,
Alex

**Comment by alejoe91** [comment]
Hi @atranvan 

Good to hear that it's fixed!

**Comment by seqasim** [comment]
This problem also arises when the jupyter environment is hosted on an online server (as is the case on our computing cluster). Even if select the correct environment as the kernel, the shell commands will still be run from the base environment and not the desired environment. 

Would it be reasonable to append sys.executable to the shell cmd so that the python interpreter used by Jupyter is always the one used to run the shell scripts? I am not too familiar with the subprocess module...

**Comment by seqasim** [comment]
> This problem also arises when the jupyter environment is hosted on an online server (as is the case on our computing cluster). Even if select the correct environment as the kernel, the shell commands will still be run from the base environment and not the desired environment.
> 
> Would it be reasonable to append sys.executable to the shell cmd so that the python interpreter used by Jupyter is always the one used to run the shell scripts? I am not too familiar with the subprocess module...

Sorry, I was being dumb. For anyone who has this issue in the future: 

In klusta.py:
            # shell_cmd = '''
            #             #!/bin/bash
            #             klusta {klusta_config} --overwrite
            #         '''.format(klusta_config=output_folder / 'config.prm')
            shell_cmd = '''
                        #!/bin/bash
                        {} {klusta_config} --overwrite
                    '''.format(os.path.join(PATH_TO_YOUR_ENV, "bin", "klusta"),
                               klusta_config=output_folder / 'config.prm')
