### ISSUE TITLE
handle parameters in a standardized way for GUI

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikesorters#8]
@colehurwitz

**Comment by colehurwitz** [comment]
Hello! I think that so far I am happy with the current GUI param situation. Currently, I set GUI params separately in each sorter. I also set GUI params in each recording extractor, preprocessor, and postprocessor. Each param is formatted in the pyqtgraph format which is a dictionary with keys: ['name',  'type', 'title']. If a default value exists for the param, then the dictionary will have:  ['name',  'type', 'value', 'default',  'title']

- 'name' has a string as the value.
- 'type' has a string as the value ('int, 'list', etc.).
-' value' is set to the default value.
- 'default' is the default value in the function.
- 'title' is the string which describes the param.

I think that is a fair approach and has worked for me so far.

**Comment by alejoe91** [comment]
closing then :)

**Comment by colehurwitz** [comment]
It might be good for me to document this process somewhere for contributors... any ideas where?

**Comment by alejoe91** [comment]
In spikesorters README. We should have a "ADD YOUR SORTER SECTION"

**Comment by colehurwitz** [comment]
Gotcha. I can put something there for that. However, GUI params exist in all repos... Maybe after I make the README/RTD for spikely, I can put it there.
