### ISSUE TITLE
Tridesclous

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spikesorters#86]
Hello,
I installed the tridesclous sorter but it does not appear in my installed sorters, and when I ran it I am asked to install it.
I restarted the kernel but still it doesn't appear even though it says the installation was successful.
I am also having trouble installing SpykingCircus even though my system is cleaned and only spikeinterface has been installed after installing anaconda.
"  Successfully built tridesclous
Installing collected packages: tridesclous
Successfully installed tridesclous-1.4.1

(base) C:\Users\lampllab>"

The only sorting algorithm I managed to install was klusta

**Comment by samuelgarcia** [comment]
What happen when you do
```tdc```
in a console ?

**Comment by benefron** [comment]
I get this error:
"ModuleNotFoundError: No module named 'hdbscan'"

**Comment by samuelgarcia** [comment]
you need to do 
conda install -c conda-forge hdbscan

or 
pip install hdbscan

see
https://tridesclous.readthedocs.io/en/latest/installation.html

**Comment by benefron** [comment]
Thank you,
this worked.
another issue
When I ran herdingspikes it starts running but then restarts my kernel

**Comment by samuelgarcia** [comment]
ask to Cole or Matthias
@colehurwitz @mhhennig

**Comment by benefron** [comment]
It is working now after updating the sorters
Thanks
