### ISSUE TITLE
Wave clus

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spikesorters#87]
I ran the wave clus sorter and I get the following exception:
"Exception: Cannot write script. No path specified"

I specified a path for the sorter at the beginning of the script as follows:
"sorters.WaveClusSorter.set_waveclus_path(r'C:\Users\lampllab\Documents\sorters\wave_clus')"

And I run the sorter as follows:
"sorting_WC = sorters.run_waveclus(recording=recording_cmr)"

for kilosort2 and ironclust this method worked but not for wav clus.

What path am I suppose to specify and where?
Thank you,
Ben

**Comment by alejoe91** [comment]
Hi @benefron 
Can you try a `pip install --upgrade spikesorters`?

There was a bug in the code :) That should fix it!

**Comment by benefron** [comment]
Now Wave clus runs
But, I get only electrodes 1-31 for wave clus. it doesn't get electrode 0. maybe because matlab starts with 1?
i get only 31 electrodes in total instead of 32.

**Comment by alejoe91** [comment]
If you are running the code I posted on spiketoolkit there was a missing channel in the common reference groups (I think channel 10). That's probably why you get 31 channels

**Comment by benefron** [comment]
OK.
I see it.
You know that it runs really really slow compared to the other algorithms? Is it the way it works or did I need to change something?
Thanks,
Ben

**Comment by alejoe91** [comment]
That's normal. WC was designed for single electrodes or a few channel max. You can test which sorters suits your data best!

**Comment by benefron** [comment]
OK
I'll close the issue
