### ISSUE TITLE
Klusta

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spikesorters#88]
I get the following exception when running klusta:

"Exception: klusta returned a non-zero exit code"

How can I debug it? I ran it on different open ephys recordings that I have.

Thank you ,
Ben

**Comment by alejoe91** [comment]
Hi,

Can you give us more info? What OS are you using? How did you install klusta? Are you running from a notebook? 

In case you are running from a notebook, you should see the klusta output in the terminal attached. That should give more information

**Comment by benefron** [comment]
I am using Windows I used pip install to install klusta .
I am new to python so I am not sure how to run from note book and get the klusta output.
It ran before but I had trouble with the anaconda and I reinstalled everything.
i will try to reinstall klusta and see if it works.
Thanks,
Ben

**Comment by benefron** [comment]
I reinstalled klusta from the installation instructions in https://github.com/kwikteam/klusta and now I get the following:
TypeError: save_to_probe_file() got an unexpected keyword argument 'grouping_property'
I get the same mistake for tridesclous

**Comment by alejoe91** [comment]
Can you paste the code you are running? 
@samuelgarcia can you look into this?

**Comment by benefron** [comment]
import os
import spikeinterface as si
import spikeinterface.extractors as se 
import spikeinterface.toolkit as st
import spikeinterface.sorters as sorters
import spikeinterface.comparison as sc
import spikeinterface.widgets as sw
import matplotlib.pylab as plt
import numpy as np


sorters.WaveClusSorter.set_waveclus_path(r'C:\Users\lampllab\Documents\sorters\wave_clus')

sorters.IronClustSorter.set_ironclust_path(r'C:\Users\lampllab\Documents\sorters\ironclust')
sorters.Kilosort2Sorter.set_kilosort2_path(r'C:\Users\lampllab\Documents\sorters\Kilosort2')
sorters.KilosortSorter.set_kilosort_path(r'C:\Users\lampllab\Documents\sorters\Kilosort')

recording = se.OpenEphysRecordingExtractor(r'D:\Data\ION\07_10_19\AudCal_2019-10-07_14-23-48')

recording_prb = recording.load_probe_file(r'C:\Users\lampllab\Documents\sorters\probes\neuronexus\A2x16-10mm-50-500-177-A32.prb')
channel_ids = recording.get_channel_ids()
fs = recording.get_sampling_frequency()
num_chan = recording.get_num_channels()


recording_f = st.preprocessing.bandpass_filter(recording_prb, freq_min=300, freq_max=6000)

recording_cmr = st.preprocessing.common_reference(recording_f,reference='median')

trace_f_snippet = recording_f.get_traces(start_frame=int(fs*0), end_frame=int(fs*600))
sw.plot_timeseries(recording_f, channel_ids=range(17))
trace_cmr_snippet = recording_cmr.get_traces(channel_ids = channel_ids,start_frame = int(0*fs), end_frame = int(30*fs))
sw.plot_timeseries(recording_cmr, channel_ids= [16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])




sorting_KL = sorters.run_klusta(recording=recording_cmr)
print('Found', len(sorting_KL.get_unit_ids()), 'units')
sorting_TR = sorters.run_tridesclous(recording=recording_cmr)
print('Found', len(sorting_TR.get_unit_ids()), 'units')

**Comment by alejoe91** [comment]
I see. I think you just need to upgrade spikeextractors:
pip install --upgrade spikeextractors

This is due to some compatibility issues with new versions of the single packages and the versions installed with the spikeinterface package.

We'll make a new release with many fixes soon

**Comment by benefron** [comment]
So now tridesclous runs but I get the original problem I had with klusta:

Traceback (most recent call last):

  File "<ipython-input-5-3f93f91bb4fe>", line 5, in <module>
    sorting_KL = sorters.run_klusta(recording=recording_cmr)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spikesorters\sorterlist.py", line 102, in run_klusta
    return run_sorter('klusta', *args, **kargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spikesorters\sorterlist.py", line 53, in run_sorter
    sorter.run()

  File "C:\ProgramData\Anaconda3\lib\site-packages\spikesorters\basesorter.py", line 110, in run
    self._run(recording, self.output_folders[i])

  File "C:\ProgramData\Anaconda3\lib\site-packages\spikesorters\klusta\klusta.py", line 150, in _run
    raise Exception('klusta returned a non-zero exit code')

Exception: klusta returned a non-zero exit code

**Comment by samuelgarcia** [comment]
Hi.
could you do
```sorting_KL = sorters.run_klusta(recording=recording_cmr, verbose=True)```

**Comment by benefron** [comment]
Did not work.
Should I uninstall and reinstall klusta?

**Comment by samuelgarcia** [comment]
Of course but do you have a longer error message ?

**Comment by benefron** [comment]
no the same

**Comment by samuelgarcia** [comment]
oups.
There must be a bug in the wrapper.
I will have a look soon.
Does klusta work independently of spikeinterface ?
Wht happen if you do "klusta" in  a console ?

**Comment by benefron** [comment]
I get two blank terminals popping and dissapearing and that it

**Comment by alejoe91** [comment]
@benefron did you get further in properly installing klusta? How did you install it?

Can you try to reinstall it using these instructions: https://spikeinterface.readthedocs.io/en/latest/sortersinfo.html

**Comment by benefron** [comment]
Klusta is running for me on the cluster, didn't check it on my desktop recently.
I am having trouble running matlab based sorters on a cluster. But it might be on my end.

**Comment by alejoe91** [comment]
ok, I'll close this then
