### ISSUE TITLE
Fix spykingcircus test on travis (and locally)

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikesorters#9]
we should force spykingcircus==0.8.0 and install mpich on travis

**Comment by samuelgarcia** [comment]
Yep.

**Comment by alejoe91** [comment]
@yger 

I can't figure out how to fix it. 

In travis I added mpich, mpi4py, pyqt5, and spikingcircus==0.8.0, but tests still fail https://github.com/SpikeInterface/spikesorters/pull/23

Any idea?

**Comment by yger** [comment]
With conda, mpich is the default. Let me know if you have issues, as said let's work with 0.8.1 from now on. I'm also not an expert in travis/appveyor and packaging :-(

**Comment by alejoe91** [comment]
Yeeeeey https://github.com/SpikeInterface/spikesorters/pull/23
