### ISSUE TITLE
Running matlab based sorters

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spikesorters#94]
Hi,
I am having trouble when running matlab based sorters (specifically in kilosort2) when the specified working directory is on a drive different than C:\\. I need to be able to work and save to a directory that is not C:.
the working folder is created but matlab is not going to that folder.
Thanks,
Ben

**Comment by alejoe91** [comment]
Hi @benefron 

I think the issue is that in Windows, the command to change to another drive is not `cd`, but `pushd`. 
Can't you run the script from the other drive?

Alessio

**Comment by benefron** [comment]
The script is running from the other drive.
The problem is both in Linux and Windows.
The problem is the directory it is tuning the shell script from is not in the same location

**Comment by alejoe91** [comment]
Are you using the latest `spikesorters`? Can you write a minimal example to reproduce this error?

**Comment by benefron** [comment]
I updated it today.
I am running spikesorters 0.2.2

The code I am running:
sorters.Kilosort2Sorter.set_kilosort2_path(r'Y:/befron/Kilosort2')
sorting_output = sorters.run_sorters(['kilosort2'], [recording_1_cmr], working_folder=r'Y:/befron/Data/ION/23_01_20/1681')
output in python:
sorters.Kilosort2Sorter.set_kilosort2_path(r'Y:/befron/Kilosort2')
WARNING! The recording contains group. In order to spike sort by 'group' use grouping_property='group' as argument.
RUNNING SHELL SCRIPT: C:\Users\lampllab\AppData\Local\Temp\tmp_shellscript05afunov\script.bat


Matlab directory when opened:
C:\Users\lampllab

Matlab error:
Unrecognized function or variable 'kilosort2_master'.

When I run the same code but change the path to C:\ everything works:
sorting_output = sorters.run_sorters(['kilosort2'], [recording_1_cmr], working_folder=r'/befron/Data/ION/23_01_20/1681')

Thanks

**Comment by benefron** [comment]
I added a line to change the working folder in my pipline
it seems to solve the problem
Thanks
