### ISSUE TITLE
Kilosort2 parameters not passed on

### ISSUE THREAD

**Issue by warnerwarner** [SpikeInterface/spikesorters#96]
When calling the Kilosort2 sorter either with run_sorter or run_Kilosort2 any additional parameter changes dont seem to be passed onto the sorter. In the kilosort_config.m file generate they all remain the same?

**Comment by warnerwarner** [comment]
Should of been more specific, its the minFR parameter in particular, and looking at the kilosort_config.m template file I dont think minFR is being used, rather the default 0.1 is

**Comment by alejoe91** [comment]
Hi @warnerwarner 

There are actually 2 parameters: `minFR` and `minfr_goodchannels`. 
The former is used during the template matching phase (templates are dropped if the firing rate is less than `minFR`). The former instead filters out bad channels (channels in which the rate of detected waveforms is less than `minfr_goodchannels`).

I think that the `minFR` option is correctly set. What we can do is also expose the `minfr_goodchannels` parameter.

**Comment by warnerwarner** [comment]
Yes, you're right! My mistake, I misread the variable. If that could be opened up that'd be really great.

Thanks!

**Comment by alejoe91** [comment]
Sure! A PR is coming :)

**Comment by alejoe91** [comment]
Can you test this? https://github.com/SpikeInterface/spikesorters/pull/97

**Comment by warnerwarner** [comment]
Works perfectly thank you!
